/* This Proc Format program was automatically generated by Stat/Transfer ver.14.2.1138.0513 */



libname library '/home/Carsten/Skrivebord/' ;

proc format library = library ;
   value V4F
      6 = 'Denmark' ;
   value V5F
      1 = 'sitting and relaxing as much as possible'  
      2 = 'doing things, being active'  
      3 = 'both equally' ;
   value V6F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V7F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V8F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V9F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V10F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V11F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V12F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V13F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V14F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V15F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V16F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V17F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V18F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V19F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V20F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V21F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V22F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V23F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V24F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V25F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V26F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V27F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V28F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V29F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V30F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V31F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V32F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V33F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V34F
      1 = 'yes'  
      2 = 'no' ;
   value V35F
      1 = 'less than one hour'  
      2 = 'between 1 - 2 hours'  
      3 = 'between 2 - 3 hours'  
      4 = 'between 3 - 4 hours'  
      5 = 'more than 4 hours'  
      6 = 'never watch TV' ;
   value V36F
      1 = 'very much'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'not at all' ;
   value V37F
      1 = 'yes, frequently'  
      2 = 'yes, sometimes'  
      3 = 'seldom'  
      4 = 'never' ;
   value V38F
      1 = 'more willing'  
      2 = 'less willing'  
      3 = 'equally willing' ;
   value V39F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V40F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V41F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V42F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V43F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V44F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V45F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V46F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V47F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V48F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V49F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V50F
      1 = 'very good'  
      2 = 'good'  
      3 = 'fair'  
      4 = 'poor'  
      5 = 'very poor' ;
   value V51F
      1 = 'yes'  
      2 = 'no' ;
   value V52F
      1 = 'yes'  
      2 = 'no' ;
   value V53F
      1 = 'yes'  
      2 = 'no' ;
   value V54F
      1 = 'yes'  
      2 = 'no' ;
   value V55F
      1 = 'yes'  
      2 = 'no' ;
   value V56F
      1 = 'yes'  
      2 = 'no' ;
   value V57F
      1 = 'yes'  
      2 = 'no' ;
   value V58F
      1 = 'yes'  
      2 = 'no' ;
   value V59F
      1 = 'yes'  
      2 = 'no' ;
   value V60F
      1 = 'yes'  
      2 = 'no' ;
   value V61F
      1 = 'most can be trusted'  
      2 = 'can''t be too careful' ;
   value V62F
      1 = '1 - none at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - a great deal' ;
   value V63F
      1 = '1 - none at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - a great deal' ;
   value V64F
      1 = '1 - none at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - a great deal' ;
   value V65F
      1 = 'very happy'  
      2 = 'quite happy'  
      3 = 'not very happy'  
      4 = 'not at all happy' ;
   value V66F
      1 = '1 - dissatisfied'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - satisfied' ;
   value V67F
      1 = '1 - dissatisfied'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - satisfied' ;
   value V68F
      1 = '1 - dissatisfied'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - satisfied' ;
   value V69F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V70F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V71F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V72F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V73F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V74F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V75F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V76F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V77F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V78F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V79F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V80F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V81F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V82F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V83F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V84F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V85F
      1 = 'look forward to work'  
      2 = 'regret the weekend is over'  
      3 = 'enjoy both the weekend and work' ;
   value V86F
      1 = 'a great deal'  
      2 = 'some'  
      3 = 'little'  
      4 = 'none' ;
   value V87F
      1 = 'often taken advantage of'  
      2 = 'sometimes'  
      3 = 'never' ;
   value V88F
      1 = '1 - none at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - a grat deal' ;
   value V89F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V90F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V91F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V92F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V93F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V94F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V95F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V96F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V97F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V98F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V99F
      1 = '1 - dissatisfied'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - satisfied' ;
   value V100F
      1 = '1 - dissatisfied'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - satisfied' ;
   value V101F
      1 = 'get a lot better'  
      2 = 'get a little better'  
      3 = 'stay the same'  
      4 = 'get a little worse'  
      5 = 'get a lot worse' ;
   value V102F
      1 = 'fair'  
      2 = 'unfair' ;
   value V103F
      1 = 'the owners should run their business or appoint the managers'  
      2 = 'the owners and the employees should participate in the selection of managers'  
      3 = 'the State should be the owner and appoint the managers'  
      4 = 'the employees should own the business and should elect the managers' ;
   value V104F
      1 = 'should follow instructions'  
      2 = 'must be convinced first'  
      3 = 'depends' ;
   value V105F
      1 = 'will help'  
      2 = 'will harm'  
      3 = 'some of each' ;
   value V106F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V107F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V108F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V109F
      1 = 'good and evil in everyone'  
      2 = 'everyone is basically good' ;
   value V110F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V111F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V112F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V113F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V114F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V115F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V116F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V117F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V118F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V119F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V120F
      1 = 'yes'  
      2 = 'no' ;
   value V121F
      1 = '1 - not at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - very' ;
   value V122F
      1 = 'agree with statement A'  
      2 = 'agree with statement B'  
      3 = 'disagree with both' ;
   value V123F
      1 = 'there is no one true religion but there are basic truths and meanings to be found in all the great religions of the worl'  
      2 = 'there is only one true religion'  
      3 = 'none of the great religions has any truths to offer' ;
   value V124F
      1 = 'Roman Catholic'  
      2 = 'protestant (Den Danske Folkekirke) (Church of England, Scotland or Wales)'  
      3 = 'indremissionsk, Jehovas Vidner, adventister (free church/non-conformist)'  
      4 = 'jew'  
      5 = 'muslim'  
      6 = 'hindu'  
      7 = 'buddhist'  
      8 = 'other'  
      9 = 'none' ;
   value V125F
      1 = 'more than once a week'  
      2 = 'once a week'  
      3 = 'once a month'  
      4 = 'Christmas/Easter day'  
      5 = 'other specific holy days'  
      6 = 'once a year'  
      7 = 'less often'  
      9 = 'never; practically never' ;
   value V126F
      1 = 'a religious person'  
      2 = 'not a religious person'  
      3 = 'a convinced atheist' ;
   value V127F
      1 = 'yes'  
      2 = 'no' ;
   value V128F
      1 = 'yes'  
      2 = 'no' ;
   value V129F
      1 = 'yes'  
      2 = 'no' ;
   value V130F
      1 = 'more important'  
      2 = 'less important'  
      3 = 'equally important' ;
   value V131F
      1 = 'yes'  
      2 = 'no' ;
   value V132F
      1 = 'yes'  
      2 = 'no' ;
   value V133F
      1 = 'yes'  
      2 = 'no' ;
   value V134F
      1 = 'yes'  
      2 = 'no' ;
   value V135F
      1 = 'yes'  
      2 = 'no' ;
   value V136F
      1 = 'yes'  
      2 = 'no' ;
   value V137F
      1 = 'yes'  
      2 = 'no' ;
   value V138F
      1 = 'yes'  
      2 = 'no' ;
   value V139F
      1 = 'there is a personal God'  
      2 = 'there is some sort of spirit or life force'  
      3 = 'I don''t really know what to think'  
      4 = 'I don''t really think there is any sort of spirit, God or life force' ;
   value V140F
      1 = '1 - not at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - very' ;
   value V141F
      1 = 'yes'  
      2 = 'no' ;
   value V142F
      1 = 'yes'  
      2 = 'no' ;
   value V143F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V144F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V145F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V146F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V147F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V148F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V149F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V150F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V151F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V152F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V153F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V154F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V155F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V156F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V157F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V158F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V159F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V160F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V161F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V162F
      1 = 'applies fully'  
      2 = 'applies to a limited extent'  
      3 = 'doesn''t apply' ;
   value V163F
      1 = 'no, never'  
      2 = 'yes' ;
   value V164F
      1 = 'no, never'  
      2 = 'yes' ;
   value V165F
      1 = 'no, never'  
      2 = 'yes' ;
   value V166F
      1 = 'no, never'  
      2 = 'yes' ;
   value V167F
      1 = 'not at all'  
      2 = 'slightly'  
      3 = 'a fair amount'  
      4 = 'quite a lot'  
      5 = 'a grat deal' ;
   value V168F
      1 = 'very close'  
      2 = 'quite close'  
      3 = 'not very close'  
      4 = 'not at all close' ;
   value V169F
      1 = 'very close'  
      2 = 'quite close'  
      3 = 'not very close'  
      4 = 'not at all close' ;
   value V170F
      1 = 'very close'  
      2 = 'quite close'  
      3 = 'not very close'  
      4 = 'not at all close' ;
   value V171F
      1 = 'very strict'  
      2 = 'quite strict'  
      3 = 'not very strict'  
      4 = 'not at all strict' ;
   value V172F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V173F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V174F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V175F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V176F
      1 = 'often'  
      2 = 'sometimes'  
      3 = 'rarely'  
      4 = 'never' ;
   value V177F
      1 = '1 - dissatisfied'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - satisfied' ;
   value V178F
      1 = 'married'  
      2 = 'living as married'  
      3 = 'divorced'  
      4 = 'separated'  
      5 = 'widowed'  
      6 = 'single - skip to Q.245 (V186)' ;
   value V179F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V180F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V181F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V182F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V183F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V184F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V185F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V186F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V187F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V188F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V189F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V190F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V191F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V192F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V193F
      1 = 'tend to agree'  
      2 = 'tend to disagree' ;
   value V194F
      1 = 'tend to agree'  
      2 = 'tend to disagree'  
      3 = 'neither/it depends' ;
   value V195F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V196F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V197F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V198F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V199F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V200F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V201F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V202F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V203F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V204F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V205F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V206F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V207F
      1 = 'very important'  
      2 = 'rather important'  
      3 = 'not very important' ;
   value V208F
      0 = 'no children'  
      1 = 'one child'  
      2 = 'two children'  
      3 = 'three children'  
      4 = 'four children'  
      5 = 'five children'  
      6 = 'six children (or more?)'  
      8 = 'don''t know' ;
   value V209F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V210F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V211F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V212F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V213F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V214F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V215F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V216F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V217F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V218F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V219F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V220F
      1 = 'tend to agree'  
      2 = 'tend to disagree' ;
   value V221F
      1 = 'needs children'  
      2 = 'not necessary' ;
   value V222F
      1 = 'tend to agree'  
      2 = 'tend to disagree'  
      3 = 'neither' ;
   value V223F
      1 = 'tend to agree with statement A'  
      2 = 'tend to agree with statement B' ;
   value V224F
      1 = 'parents'' duty is to do their best for their children even at the expense of their own well-being'  
      2 = 'parents have a life of their own and should not be asked to sacrifice their own well-being for the sake of their childre'  
      3 = 'neither' ;
   value V225F
      1 = 'approve'  
      2 = 'disapprove'  
      3 = 'depends' ;
   value V226F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V227F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V228F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V229F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V230F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V231F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V232F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V233F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V234F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V235F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V236F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V237F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V238F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V239F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V240F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V241F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V242F
      0 = 'not mentioned'  
      1 = 'mentioned' ;
   value V243F
      1 = 'yes'  
      2 = 'no' ;
   value V244F
      1 = 'one child'  
      2 = 'two children'  
      3 = 'three children'  
      4 = 'four children'  
      5 = 'five children'  
      6 = 'six children'  
      7 = 'seven children'  
      8 = 'eight children'  
      9 = 'nine children (or more?)' ;
   value V245F
      1 = 'I take an active interest in politics'  
      2 = 'I am interested in politics but don''t take any active part'  
      3 = 'my interest in politics is not greater than other interests'  
      4 = 'I''m not interested in politics at all' ;
   value V246F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V247F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V248F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V249F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V250F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V251F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V252F
      1 = 'have done'  
      2 = 'might do'  
      3 = 'would never do' ;
   value V253F
      1 = 'agree with A'  
      2 = 'agree with B'  
      3 = 'neither' ;
   value V254F
      1 = '1 - none at all'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - a great deal' ;
   value V255F
      1 = 'the entire way our society is organised must be radically changed by revolutionary action'  
      2 = 'our society must be gradually improved by reforms'  
      3 = 'our present society must be valiantly defended against all subversive forces' ;
   value V256F
      1 = 'maintaining order in the nation'  
      2 = 'giving the people more say in important government decisions'  
      3 = 'fighting rising prices'  
      4 = 'protecting freedom of speech' ;
   value V257F
      1 = 'maintaining order in the nation'  
      2 = 'giving the people more say in important government decisions'  
      3 = 'fighting rising prices'  
      4 = 'protecting freedom of speech' ;
   value V258F
      1 = 'agree with A'  
      2 = 'agree with B'  
      3 = 'agree with C'  
      4 = 'agree with D' ;
   value V259F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V260F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V261F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V262F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V263F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V264F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V265F
      1 = 'good'  
      2 = 'bad'  
      3 = 'don''t mind' ;
   value V266F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V267F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V268F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V269F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V270F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V271F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V272F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V273F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V274F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V275F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V276F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V277F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V278F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V279F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V280F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V281F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V282F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V283F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V284F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V285F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V286F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V287F
      1 = '1 - can never be justified'  
      2 = '2'  
      3 = '3'  
      4 = '4'  
      5 = '5'  
      6 = '6'  
      7 = '7'  
      8 = '8'  
      9 = '9'  
      10 = '10 - can always be justified' ;
   value V288F
      1 = 'regular drinker'  
      2 = 'drink rather often'  
      3 = 'occasional drinker'  
      4 = 'total abstainer'  
      5 = 'not answered' ;
   value V289F
      1 = 'less than most'  
      2 = 'same as most'  
      3 = 'more than most'  
      4 = 'not answered' ;
   value V290F
      1 = 'very serious'  
      2 = 'quite serious'  
      3 = 'not very serious'  
      4 = 'not at all serious' ;
   value V291F
      1 = 'very serious'  
      2 = 'quite serious'  
      3 = 'not very serious'  
      4 = 'not at all serious' ;
   value V292F
      1 = 'approve'  
      2 = 'disapprove' ;
   value V293F
      1 = 'approve'  
      2 = 'disapprove' ;
   value V294F
      1 = 'approve'  
      2 = 'disapprove' ;
   value V295F
      1 = 'approve'  
      2 = 'disapprove' ;
   value V296F
      1 = 'often'  
      2 = 'from time to time'  
      3 = 'rarely'  
      4 = 'never' ;
   value V297F
      1 = 'frequently'  
      2 = 'occasionally'  
      3 = 'never' ;
   value V298F
      1 = 'yes'  
      2 = 'no - skip to Q.346 (V301)' ;
   value V299F
      1 = 'Socialdemokratiet'  
      2 = 'Radikale Venstre'  
      3 = 'Konservative Folkeparti'  
      4 = 'Danmarks Retsforbund'  
      5 = 'Socialistisk Folkeparti'  
      6 = 'Kommunisterne'  
      7 = 'Centrum-Demokraterne'  
      8 = 'Kristeligt Folkeparti'  
      9 = 'Venstre'  
      10 = 'Venstresocialisterne'  
      11 = 'Fremskridtspartiet'  
      99 = 'no answer' ;
   value V300F
      1 = 'very close'  
      2 = 'fairly close'  
      3 = 'merely a sympathiser'  
      4 = 'close to no particular party' ;
   value V301F
      1 = 'locality of town where you live'  
      2 = 'region or country where you live'  
      3 = 'your country as a whole'  
      4 = 'Europe'  
      5 = 'the world as a whole' ;
   value V302F
      1 = 'locality of town where you live'  
      2 = 'region or country where you live'  
      3 = 'your country as a whole'  
      4 = 'Europe'  
      5 = 'the world as a whole' ;
   value V303F
      1 = 'very proud'  
      2 = 'quite proud'  
      3 = 'not very proud'  
      4 = 'not at all proud' ;
   value V304F
      1 = 'tend to agree with A'  
      2 = 'tend to agree with B'  
      3 = 'neither' ;
   value V305F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V306F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V307F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V308F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V309F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V310F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V311F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V312F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V313F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V314F
      1 = 'a great deal'  
      2 = 'quite a lot'  
      3 = 'not very much'  
      4 = 'none at all' ;
   value V315F
      1 = 'tend to agree'  
      2 = 'tend to disagree' ;
   value V316F
      1 = 'house'  
      2 = 'apartment'  
      3 = 'other' ;
   value V317F
      1 = 'own - paid for, buying with mortgage'  
      2 = 'rent from municipality/council'  
      3 = 'rent privately'  
      4 = 'hostel, lodging, squatters, etc.' ;
   value V318F
      1 = '12 or under'  
      2 = '13'  
      3 = '14'  
      4 = '15'  
      5 = '16'  
      6 = '17'  
      7 = '18'  
      8 = '19'  
      9 = '20'  
      10 = '21 or over' ;
   value V319F
      1 = 'one'  
      2 = 'two'  
      3 = 'three'  
      4 = 'four'  
      5 = 'five'  
      6 = 'six'  
      7 = 'seven'  
      8 = 'eight' ;
   value V320F
      0 = 'not present'  
      1 = 'present' ;
   value V321F
      0 = 'not present'  
      1 = 'present' ;
   value V322F
      0 = 'not present'  
      1 = 'present' ;
   value V323F
      0 = 'not present'  
      1 = 'present' ;
   value V324F
      0 = 'not present'  
      1 = 'present' ;
   value V325F
      1 = 'yes'  
      2 = 'no' ;
   value V326F
      1 = 'full-time (30 hours a week or more)'  
      2 = 'part-time (less than 30 hours a week)'  
      3 = 'self-employed'  
      4 = 'unemployed'  
      5 = 'retired; pensioned'  
      6 = 'housewife not otherwise employed'  
      7 = 'student' ;
   value V327F
      1 = 'employers and managers of large establishments (over 500 employees)'  
      2 = 'employers and managers of small establishments (under 500 employees)'  
      3 = 'professional workers - lawyers, accountants, teachers, etc.'  
      4 = 'middle level non-manual - office worker etc.'  
      5 = 'junior level non-manual - office worker etc.'  
      6 = 'foreman and supervisor - manual'  
      7 = 'skilled manual workers'  
      8 = 'semi-skilled manual workers'  
      9 = 'unskilled manual workers'  
      10 = 'farmers - employers, managers and own account'  
      11 = 'agricultural workers'  
      12 = 'member of armed forces' ;
   value V328F
      1 = 'yes'  
      2 = 'no - go back and ask Q.365/367 for chief wage earner' ;
   value V329F
      1 = 'full-time (30 hours a week or more)'  
      2 = 'part-time (under 30 hours a week)'  
      3 = 'self-employed'  
      4 = 'unemployed'  
      5 = 'retired; pensioned'  
      6 = 'housewife not otherwise employed'  
      7 = 'student'  
      10 = 'not applicable' ;
   value V330F
      1 = 'employers and managers of large establishments (over 500 employees)'  
      2 = 'employers and managers of small establishments (under 500 employees)'  
      3 = 'professional workers - lawyers, accountants, teachers etc.'  
      4 = 'middle level non-manual - office worker etc.'  
      5 = 'junior level non-manual - office worker etc.'  
      6 = 'foreman and supervisor - manual'  
      7 = 'skilled manual workers'  
      8 = 'semi-skilled manual workers'  
      9 = 'unskilled manual workers'  
      10 = 'farmers - employers, managers and own account'  
      11 = 'agricultural workers'  
      12 = 'member of the armed forces' ;
   value V331F
      1 = '1'  
      2 = '2'  
      3 = '3-5'  
      4 = '6-9'  
      5 = '10-25'  
      6 = '26-99'  
      7 = '100-249'  
      8 = '250-1000'  
      9 = 'more than 1000' ;
   value V332F
      1 = 'yes, self'  
      2 = 'yes, spouse'  
      3 = 'no' ;
   value V333F
      1 = 'male'  
      2 = 'female, housewife'  
      3 = 'female, not housewife (udearbejdende)' ;
   value V335F
      1 = 'code 1'  
      2 = 'code 2'  
      3 = 'code 3'  
      4 = 'code 4'  
      5 = 'code 5'  
      6 = 'code 6'  
      7 = 'code 7'  
      8 = 'code 8'  
      9 = 'code 9'  
      10 = 'code 10'  
      11 = 'code 11'  
      12 = 'code 12'  
      99 = 'code 99' ;
   value V336F
      1 = 'less than 60.000 Dkr.'  
      2 = '60.000 - 79.999 Dkr.'  
      3 = '80.000 - 99.999 Dkr.'  
      4 = '100.000 - 124.999 Dkr.'  
      5 = '125.000 - 149.999 Dkr.'  
      6 = '150.000 - 199.999 Dkr.'  
      7 = '200.000 - 249.999 Dkr.'  
      8 = '250.000 Dkr. and more'  
      99 = 'no answer' ;
   value V337F
      1 = 'AB (professional/managerial, above average life style)'  
      2 = 'C1 (sales, clerical and other non-manual)'  
      3 = 'C2 (manual workers - skilled, i.e. served an apprenticeship)'  
      4 = 'DE (semi-skilled, unskilled or unemployed or pensioner)' ;
   value V338F
      1 = 'very self-assured'  
      2 = 'fairly self-assured'  
      3 = 'a bit unsure of him/herself'  
      4 = 'fairly unsure' ;
   value V339F
      1 = 'quite cheerful'  
      2 = 'not so cheerful'  
      3 = 'impossible to say' ;

proc datasets library = library ;
modify Data829;
   format        V4 V4F.;
   format        V5 V5F.;
   format        V6 V6F.;
   format        V7 V7F.;
   format        V8 V8F.;
   format        V9 V9F.;
   format       V10 V10F.;
   format       V11 V11F.;
   format       V12 V12F.;
   format       V13 V13F.;
   format       V14 V14F.;
   format       V15 V15F.;
   format       V16 V16F.;
   format       V17 V17F.;
   format       V18 V18F.;
   format       V19 V19F.;
   format       V20 V20F.;
   format       V21 V21F.;
   format       V22 V22F.;
   format       V23 V23F.;
   format       V24 V24F.;
   format       V25 V25F.;
   format       V26 V26F.;
   format       V27 V27F.;
   format       V28 V28F.;
   format       V29 V29F.;
   format       V30 V30F.;
   format       V31 V31F.;
   format       V32 V32F.;
   format       V33 V33F.;
   format       V34 V34F.;
   format       V35 V35F.;
   format       V36 V36F.;
   format       V37 V37F.;
   format       V38 V38F.;
   format       V39 V39F.;
   format       V40 V40F.;
   format       V41 V41F.;
   format       V42 V42F.;
   format       V43 V43F.;
   format       V44 V44F.;
   format       V45 V45F.;
   format       V46 V46F.;
   format       V47 V47F.;
   format       V48 V48F.;
   format       V49 V49F.;
   format       V50 V50F.;
   format       V51 V51F.;
   format       V52 V52F.;
   format       V53 V53F.;
   format       V54 V54F.;
   format       V55 V55F.;
   format       V56 V56F.;
   format       V57 V57F.;
   format       V58 V58F.;
   format       V59 V59F.;
   format       V60 V60F.;
   format       V61 V61F.;
   format       V62 V62F.;
   format       V63 V63F.;
   format       V64 V64F.;
   format       V65 V65F.;
   format       V66 V66F.;
   format       V67 V67F.;
   format       V68 V68F.;
   format       V69 V69F.;
   format       V70 V70F.;
   format       V71 V71F.;
   format       V72 V72F.;
   format       V73 V73F.;
   format       V74 V74F.;
   format       V75 V75F.;
   format       V76 V76F.;
   format       V77 V77F.;
   format       V78 V78F.;
   format       V79 V79F.;
   format       V80 V80F.;
   format       V81 V81F.;
   format       V82 V82F.;
   format       V83 V83F.;
   format       V84 V84F.;
   format       V85 V85F.;
   format       V86 V86F.;
   format       V87 V87F.;
   format       V88 V88F.;
   format       V89 V89F.;
   format       V90 V90F.;
   format       V91 V91F.;
   format       V92 V92F.;
   format       V93 V93F.;
   format       V94 V94F.;
   format       V95 V95F.;
   format       V96 V96F.;
   format       V97 V97F.;
   format       V98 V98F.;
   format       V99 V99F.;
   format      V100 V100F.;
   format      V101 V101F.;
   format      V102 V102F.;
   format      V103 V103F.;
   format      V104 V104F.;
   format      V105 V105F.;
   format      V106 V106F.;
   format      V107 V107F.;
   format      V108 V108F.;
   format      V109 V109F.;
   format      V110 V110F.;
   format      V111 V111F.;
   format      V112 V112F.;
   format      V113 V113F.;
   format      V114 V114F.;
   format      V115 V115F.;
   format      V116 V116F.;
   format      V117 V117F.;
   format      V118 V118F.;
   format      V119 V119F.;
   format      V120 V120F.;
   format      V121 V121F.;
   format      V122 V122F.;
   format      V123 V123F.;
   format      V124 V124F.;
   format      V125 V125F.;
   format      V126 V126F.;
   format      V127 V127F.;
   format      V128 V128F.;
   format      V129 V129F.;
   format      V130 V130F.;
   format      V131 V131F.;
   format      V132 V132F.;
   format      V133 V133F.;
   format      V134 V134F.;
   format      V135 V135F.;
   format      V136 V136F.;
   format      V137 V137F.;
   format      V138 V138F.;
   format      V139 V139F.;
   format      V140 V140F.;
   format      V141 V141F.;
   format      V142 V142F.;
   format      V143 V143F.;
   format      V144 V144F.;
   format      V145 V145F.;
   format      V146 V146F.;
   format      V147 V147F.;
   format      V148 V148F.;
   format      V149 V149F.;
   format      V150 V150F.;
   format      V151 V151F.;
   format      V152 V152F.;
   format      V153 V153F.;
   format      V154 V154F.;
   format      V155 V155F.;
   format      V156 V156F.;
   format      V157 V157F.;
   format      V158 V158F.;
   format      V159 V159F.;
   format      V160 V160F.;
   format      V161 V161F.;
   format      V162 V162F.;
   format      V163 V163F.;
   format      V164 V164F.;
   format      V165 V165F.;
   format      V166 V166F.;
   format      V167 V167F.;
   format      V168 V168F.;
   format      V169 V169F.;
   format      V170 V170F.;
   format      V171 V171F.;
   format      V172 V172F.;
   format      V173 V173F.;
   format      V174 V174F.;
   format      V175 V175F.;
   format      V176 V176F.;
   format      V177 V177F.;
   format      V178 V178F.;
   format      V179 V179F.;
   format      V180 V180F.;
   format      V181 V181F.;
   format      V182 V182F.;
   format      V183 V183F.;
   format      V184 V184F.;
   format      V185 V185F.;
   format      V186 V186F.;
   format      V187 V187F.;
   format      V188 V188F.;
   format      V189 V189F.;
   format      V190 V190F.;
   format      V191 V191F.;
   format      V192 V192F.;
   format      V193 V193F.;
   format      V194 V194F.;
   format      V195 V195F.;
   format      V196 V196F.;
   format      V197 V197F.;
   format      V198 V198F.;
   format      V199 V199F.;
   format      V200 V200F.;
   format      V201 V201F.;
   format      V202 V202F.;
   format      V203 V203F.;
   format      V204 V204F.;
   format      V205 V205F.;
   format      V206 V206F.;
   format      V207 V207F.;
   format      V208 V208F.;
   format      V209 V209F.;
   format      V210 V210F.;
   format      V211 V211F.;
   format      V212 V212F.;
   format      V213 V213F.;
   format      V214 V214F.;
   format      V215 V215F.;
   format      V216 V216F.;
   format      V217 V217F.;
   format      V218 V218F.;
   format      V219 V219F.;
   format      V220 V220F.;
   format      V221 V221F.;
   format      V222 V222F.;
   format      V223 V223F.;
   format      V224 V224F.;
   format      V225 V225F.;
   format      V226 V226F.;
   format      V227 V227F.;
   format      V228 V228F.;
   format      V229 V229F.;
   format      V230 V230F.;
   format      V231 V231F.;
   format      V232 V232F.;
   format      V233 V233F.;
   format      V234 V234F.;
   format      V235 V235F.;
   format      V236 V236F.;
   format      V237 V237F.;
   format      V238 V238F.;
   format      V239 V239F.;
   format      V240 V240F.;
   format      V241 V241F.;
   format      V242 V242F.;
   format      V243 V243F.;
   format      V244 V244F.;
   format      V245 V245F.;
   format      V246 V246F.;
   format      V247 V247F.;
   format      V248 V248F.;
   format      V249 V249F.;
   format      V250 V250F.;
   format      V251 V251F.;
   format      V252 V252F.;
   format      V253 V253F.;
   format      V254 V254F.;
   format      V255 V255F.;
   format      V256 V256F.;
   format      V257 V257F.;
   format      V258 V258F.;
   format      V259 V259F.;
   format      V260 V260F.;
   format      V261 V261F.;
   format      V262 V262F.;
   format      V263 V263F.;
   format      V264 V264F.;
   format      V265 V265F.;
   format      V266 V266F.;
   format      V267 V267F.;
   format      V268 V268F.;
   format      V269 V269F.;
   format      V270 V270F.;
   format      V271 V271F.;
   format      V272 V272F.;
   format      V273 V273F.;
   format      V274 V274F.;
   format      V275 V275F.;
   format      V276 V276F.;
   format      V277 V277F.;
   format      V278 V278F.;
   format      V279 V279F.;
   format      V280 V280F.;
   format      V281 V281F.;
   format      V282 V282F.;
   format      V283 V283F.;
   format      V284 V284F.;
   format      V285 V285F.;
   format      V286 V286F.;
   format      V287 V287F.;
   format      V288 V288F.;
   format      V289 V289F.;
   format      V290 V290F.;
   format      V291 V291F.;
   format      V292 V292F.;
   format      V293 V293F.;
   format      V294 V294F.;
   format      V295 V295F.;
   format      V296 V296F.;
   format      V297 V297F.;
   format      V298 V298F.;
   format      V299 V299F.;
   format      V300 V300F.;
   format      V301 V301F.;
   format      V302 V302F.;
   format      V303 V303F.;
   format      V304 V304F.;
   format      V305 V305F.;
   format      V306 V306F.;
   format      V307 V307F.;
   format      V308 V308F.;
   format      V309 V309F.;
   format      V310 V310F.;
   format      V311 V311F.;
   format      V312 V312F.;
   format      V313 V313F.;
   format      V314 V314F.;
   format      V315 V315F.;
   format      V316 V316F.;
   format      V317 V317F.;
   format      V318 V318F.;
   format      V319 V319F.;
   format      V320 V320F.;
   format      V321 V321F.;
   format      V322 V322F.;
   format      V323 V323F.;
   format      V324 V324F.;
   format      V325 V325F.;
   format      V326 V326F.;
   format      V327 V327F.;
   format      V328 V328F.;
   format      V329 V329F.;
   format      V330 V330F.;
   format      V331 V331F.;
   format      V332 V332F.;
   format      V333 V333F.;
   format      V335 V335F.;
   format      V336 V336F.;
   format      V337 V337F.;
   format      V338 V338F.;
   format      V339 V339F.;
quit;
