/* This Proc Format program was automatically generated by Stat/Transfer ver.14.3.1163.0727 */

/* ENCODING CP1252 */



libname library 'xxxxx/' ;

proc format library = library ;
   value V3F
      1981 = '1981'  
      1990 = '1990'  
      1999 = '1999'  
      2008 = '2008'  
      2017 = '2017' ;
   value V9F
      0 = 'Intervieweradministreret CAPI (dør-til-dør)'  
      1 = 'Selvadministreret CAWI (web) og PAPI (postal)' ;
   value LABA
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke' ;
   value V19F
      1 = 'Meget lykkelig'  
      2 = 'Ret lykkelig'  
      3 = 'Ikke særlig lykkelig'  
      4 = 'Slet ikke lykkelig'  
      8 = 'Ved ikke' ;
   value V20F
      1 = 'Meget godt'  
      2 = 'Godt'  
      3 = 'Nogenlunde'  
      4 = 'Dårligt'  
      5 = 'Meget dårligt'  
      8 = 'Ved ikke' ;
   value LABB
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V33F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value LABC
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V44F
      1 = 'De fleste er til at stole på'  
      2 = 'Man kan ikke være for forsigtig'  
      8 = 'Ved ikke' ;
   value LABD
      1 = 'Stor tillid'  
      2 = 'Nogen tillid'  
      3 = 'Næsten ingen tillid'  
      4 = 'Ingen tillid'  
      8 = 'Ved ikke' ;
   value V51F
      1 = 'Overhovedet ingen indflydelse'  
      10 = 'Overordentlig megen indflydelse'  
      88 = 'Ved ikke' ;
   value V52F
      1 = 'Meget utilfreds'  
      10 = 'Meget tilfreds'  
      88 = 'Ved ikke' ;
   value LABE
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value LABF
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V65F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V66F
      1 = 'Folkekirken'  
      2 = 'Islamisk trossamfund'  
      3 = 'Buddhistisk trossamfund'  
      4 = 'Hinduistisk trossamfund'  
      5 = 'Mosaisk trossamfund'  
      6 = 'Asatro'  
      7 = 'Andet'  
      8 = 'Ved ikke' ;
   value V68F
      1 = 'Folkekirken'  
      2 = 'Islamisk trossamfund'  
      3 = 'Buddhistisk trossamfund'  
      4 = 'Hinduistisk trossamfund'  
      5 = 'Mosaisk trossamfund'  
      6 = 'Asatro'  
      7 = 'Andet'  
      8 = 'Ved ikke' ;
   value V69F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V70F
      1 = 'Oftere end 1 gang om ugen'  
      2 = 'Ca. 1 gang om ugen'  
      3 = 'Ca. 1 gang om måneden'  
      4 = 'Ved særlige højtider (herunder jul og påske)'  
      5 = 'Ca. 1 gang om året'  
      6 = 'Sjældnere end 1 gang om året'  
      7 = 'Aldrig, næsten aldrig'  
      8 = 'Ved ikke' ;
   value V71F
      1 = 'Oftere end 1 gang om ugen'  
      2 = 'Ca. 1 gang om ugen'  
      3 = 'Ca. 1 gang om måneden'  
      4 = 'Ved særlige højtider (herunder jul og påske)'  
      5 = 'Ca. 1 gang om året'  
      6 = 'Sjældnere end 1 gang om året'  
      7 = 'Aldrig, næsten aldrig'  
      8 = 'Ved ikke' ;
   value V72F
      1 = 'Et troende menneske'  
      2 = 'Et ikke troende menneske'  
      3 = 'Overbevist ateist'  
      8 = 'Ved ikke' ;
   value LABG
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V78F
      1 = 'Der er en personlig Gud'  
      2 = 'Der er en særlig åndelig kraft'  
      3 = 'Jeg ved ikke, hvad jeg skal tro'  
      4 = 'Jeg tror ikke der er nogen åndelig kraft eller personlig Gud'  
      8 = 'Ved ikke' ;
   value V79F
      1 = '1. Slet ingen rolle'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Meget stor rolle'  
      88 = 'Ved ikke' ;
   value V80F
      1 = 'Hver dag'  
      2 = 'Mere end 1 gang om ugen'  
      3 = '1 gang om ugen'  
      4 = 'Mindst 1 gang om måneden'  
      5 = 'Flere gange om året'  
      6 = 'Sjældnere'  
      7 = 'Aldrig'  
      8 = 'Ved ikke' ;
   value LABH
      1 = 'Meget vigtig'  
      2 = 'Ret vigtig'  
      3 = 'Ikke særlig vigtig'  
      8 = 'Ved ikke' ;
   value V87F
      1 = 'Enig'  
      2 = 'Uenig'  
      8 = 'Ved ikke' ;
   value LABI
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value LABJ
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value LABK
      1 = 'Helt enig/enig'  
      2 = 'Hverken enig eller uenig'  
      3 = 'Uenig/helt uenig'  
      8 = 'Ved ikke' ;
   value LABL
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V115F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Ikke særlig interesseret'  
      4 = 'Slet ikke interesseret'  
      8 = 'Ved ikke' ;
   value LABM
      1 = 'Har deltaget'  
      2 = 'Ville muligvis deltage'  
      3 = 'Ville aldrig deltage'  
      8 = 'Ved ikke' ;
   value V120F
      1 = '1. Venstreorienteret'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Højreorienteret'  
      88 = 'Ved ikke' ;
   value V121F
      1 = '1. Den enkelte skal tage mere ansvar for at forsørge sig selv'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Staten skal tage mere ansvar for at sikre forsørgelse af alle'  
      88 = 'Ved ikke' ;
   value V122F
      1 = '1. Arbejdsløse skal tage et hvilket som helst ledigt job for at bevare retten t'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Arbejdsløse skal have ret til at nægte at tage et job, de ikke ønsker'  
      88 = 'Ved ikke' ;
   value V123F
      1 = '1. Konkurrence er godt'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Konkurrence er skadeligt'  
      88 = 'Ved ikke' ;
   value V124F
      1 = '1. Der skal være større indkomstmæssig lighed'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Der skal være større økonomisk tilskyndelse til at gøre en indsats for d'  
      88 = 'Ved ikke' ;
   value V125F
      1 = '1. Privatisering skal øges'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Virksomheder skal i højere grad være statsejede'  
      88 = 'Ved ikke' ;
   value LABN
      1 = 'Høj økonomisk vækst'  
      2 = 'Sikre et stærkt forsvar'  
      3 = 'Give folk større indflydelse på deres job og lokalsamfund'  
      4 = 'Forsøge at forskønne vores byer og landområder'  
      8 = 'Ved ikke' ;
   value LABO
      1 = 'At opretholde lov og orden i landet'  
      2 = 'At lade folk bestemme mere i vigtige regeringsbeslutninger'  
      3 = 'At bekæmpe stigende priser'  
      4 = 'At beskytte ytringsfriheden'  
      8 = 'Ved ikke' ;
   value V130F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value LABP
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke' ;
   value LABQ
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V151F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V152F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V153F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V154F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V155F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V156F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V157F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V158F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V159F
      0 = 'Uforeneligt med demokrati'  
      1 = '1. Ikke et vigtigt kendetegn for demokrati'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Vigtigt kendetegn for demokrati'  
      11 = 'Det er ikke foreneligt med demokrati'  
      88 = 'Ved ikke' ;
   value V160F
      1 = '1. Slet ikke vigtigt'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Meget vigtigt'  
      88 = 'Ved ikke' ;
   value V161F
      1 = '1. Set ikke demokratisk'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Fuldt demokratisk'  
      88 = 'Ved ikke' ;
   value V162F
      1 = '1. Slet ikke tilfreds'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Meget tilfreds'  
      88 = 'Ved ikke' ;
   value LABR
      1 = 'Meget godt'  
      2 = 'Temmelig godt'  
      3 = 'Temmelig dårligt'  
      4 = 'Meget dårligt'  
      8 = 'Ved ikke' ;
   value LABS
      1 = '1. Slet ikke'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. I høj grad'  
      88 = 'Ved ikke' ;
   value LABT
      1 = 'Meget tæt'  
      2 = 'Tæt'  
      3 = 'Ikke særlig tæt'  
      4 = 'Slet ikke tæt'  
      8 = 'Ved ikke' ;
   value V187F
      1 = 'Ja, gå til spm. 47'  
      2 = 'Nej, gå til spm. 48'  
      8 = 'Ved ikke' ;
   value V188F
      1 = 'Meget stolt'  
      2 = 'Ret stolt'  
      3 = 'Ikke særlig stolt'  
      4 = 'Slet ikke stolt'  
      8 = 'Ved ikke' ;
   value LABU
      1 = 'Altid'  
      2 = 'Sædvanligvis'  
      3 = 'Aldrig'  
      7 = 'Har ikke stemmeret'  
      8 = 'Ved ikke' ;
   value V192F
      1 = 'Socialdemokraterne'  
      2 = 'Det Radikale Venstre'  
      3 = 'Det Konservative Folkeparti'  
      4 = 'Socialistisk Folkeparti'  
      5 = 'Dansk Folkeparti'  
      6 = 'Nye Borgerlige'  
      7 = 'Venstre, Danmarks Liberale Parti'  
      8 = 'Liberal Alliance'  
      9 = 'Enhedslisten'  
      10 = 'Alternativet'  
      11 = 'Vil stemme blankt'  
      88 = 'Ved ikke' ;
   value V193F
      1 = 'Socialdemokraterne'  
      2 = 'Det Radikale Venstre'  
      3 = 'Det Konservative Folkeparti'  
      4 = 'Socialistisk Folkeparti'  
      5 = 'Dansk Folkeparti'  
      6 = 'Nye Borgerlige'  
      7 = 'Venstre, Danmarks Liberale Parti'  
      8 = 'Liberal Alliance'  
      9 = 'Enhedslisten'  
      10 = 'Alternativet'  
      11 = 'Vil stemme blankt'  
      88 = 'Ved ikke' ;
   value LABV
      1 = 'Meget ofte'  
      2 = 'Temmelig ofte'  
      3 = 'Sjældent'  
      4 = 'Aldrig'  
      8 = 'Ved ikke' ;
   value V202F
      1 = 'Meget dårligt'  
      2 = 'Temmelig dårligt'  
      3 = 'Hverken godt eller dårligt'  
      4 = 'Temmelig godt'  
      5 = 'Meget godt'  
      8 = 'Ved ikke' ;
   value V203F
      1 = '1. Indvandrere tager jobs fra danskere'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Indvandrere tager ikke jobs fra danskere'  
      88 = 'Ved ikke' ;
   value V204F
      1 = '1. Indvandrere gør problemerne med kriminalitet værre'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Indvandrere gør ikke problemerne med kriminalitet værre'  
      88 = 'Ved ikke' ;
   value V205F
      1 = '1. Indvandrere belaster velfærdssystemet'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Indvandrere belaster ikke velfærdssystemet'  
      88 = 'Ved ikke' ;
   value V206F
      1 = '1. Samfundet er bedst tjent med at indvandrere fastholder deres egne skikke og t'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Samfundet er bedst tjent med, at indvandrere ikke fastholder deres skikke og'  
      88 = 'Ved ikke' ;
   value LABW
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke' ;
   value V216F
      1 = '1. Udvidelsen skal fortsætte'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = '10. Udvidelsen er gået for vidt'  
      88 = 'Ved ikke' ;
   value LABX
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V222F
      1 = 'Beskyttelse af miljøet bør prioriteres, selv hvis det betyder lavere økonomisk vækst og tab af jobs'  
      2 = 'Økonomisk vækst og jobskabelse bør have førsteprioritet, selv hvis det i nogen grad går ud over miljøet'  
      3 = 'Andet spontant svar'  
      8 = 'Ved ikke' ;
   value LABY
      1 = 'Skal helt sikkert have denne ret'  
      2 = 'Skal formentlig have denne ret'  
      3 = 'Skal formentlig ikke have denne ret'  
      4 = 'Skal helt sikkert ikke have denne ret'  
      8 = 'Ved ikke' ;
   value LABZ
      1 = 'Hver dag'  
      2 = 'Flere gange om ugen'  
      3 = 'En eller to gange om ugen'  
      4 = 'Sjældent'  
      5 = 'Aldrig'  
      8 = 'Ved ikke' ;
   value LABAA
      1 = 'I høj grad'  
      2 = 'I nogen grad'  
      3 = 'Til en vis grad'  
      4 = 'I mindre grad'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke' ;
   value LABAB
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke' ;
   value V243F
      1 = 'Mand'  
      2 = 'Kvinde' ;
   value LABAC
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V252F
      1 = 'Gift'  
      2 = 'Registreret partnerskab'  
      3 = 'Enke/Enkemand'  
      4 = 'Fraskilt'  
      5 = 'Frasepareret'  
      6 = 'Har aldrig indgået ægteskab eller registreret partnerskab'  
      8 = 'Ved ikke' ;
   value LABAD
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V256F
      1 = 'Nej'  
      2 = 'Ja, mine forældre'  
      3 = 'Ja, mine svigerforældre'  
      4 = 'Ja, både mine forældre og svigerforældre'  
      8 = 'Ved ikke' ;
   value V263F
      1 = 'Ingen skolegang. Børnehaveklasse. 1.-5. klasse.'  
      2 = 'Folkeskole 6.-8. klasse'  
      3 = 'Folkeskole 9.-10. klasse'  
      4 = 'Gymnasielle uddannelser, studentereksamen, HF, HHX, HTX'  
      5 = 'Kort erhvervsuddannelse under 1-2 års varighed, F.eks. AMU Arbejdsmarkedsuddann'  
      6 = 'Faglig uddannelse (håndværk, handel, landbrug mv.), F.eks. Faglærte, Social-'  
      7 = 'Kort videregående uddannelse af op til 2-3 års varighed, F.eks. Erhvervsakadem'  
      8 = 'Mellemlang videregående uddannelse af 3-4 års varighed. Professionsbachelorer,'  
      9 = 'Universitetsbachelor. 1. del af kandidatuddannelse'  
      10 = 'Lang videregående uddannelse. Kandidatuddannelser af 5.-6. års varighed, F.eks'  
      11 = 'Licentiat'  
      12 = 'Forskeruddannelse. Ph.d., doktor'  
      13 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke' ;
   value V264F
      1 = '30 timer om ugen eller derover'  
      2 = 'Mindre end 30 timer om ugen'  
      3 = 'Selvstændig'  
      4 = 'Værnepligtig'  
      5 = 'Efterlønner/pensionist'  
      6 = 'Hjemmegående'  
      7 = 'Studerende'  
      8 = 'Arbejdsløs'  
      9 = 'Handicappet'  
      10 = 'Andet'  
      88 = 'Ved ikke' ;
   value V266F
      1 = 'Ansat'  
      2 = 'Selvstændig'  
      6 = 'Har aldrig haft et lønnet job'  
      8 = 'Ved ikke' ;
   value V268F
      1 = 'Ingen'  
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke' ;
   value V269F
      1 = 'Ja, gå til spm. 86A'  
      2 = 'Nej, gå til spm. 87'  
      8 = 'Ved ikke' ;
   value V270F
      1 = '1-9'  
      2 = '10-24'  
      3 = '25 eller flere'  
      8 = 'Ved ikke' ;
   value V271F
      1 = 'En statslig eller anden offentlig institution'  
      2 = 'En privat virksomhed'  
      3 = 'En privat organisation med almennyttigt formål'  
      8 = 'Ved ikke' ;
   value V272F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V274F
      1 = 'Ingen skolegang. Børnehaveklasse. 1.-5. klasse.'  
      2 = 'Folkeskole 6.-8. klasse'  
      3 = 'Folkeskole 9.-10. klasse'  
      4 = 'Gymnasielle uddannelser, studentereksamen, HF, HHX, HTX'  
      5 = 'Kort erhvervsuddannelse under 1-2 års varighed, F.eks. AMU Arbejdsmarkedsuddann'  
      6 = 'Faglig uddannelse (håndværk, handel, landbrug mv.), F.eks. Faglærte, Social-'  
      7 = 'Kort videregående uddannelse af op til 2-3 års varighed, F.eks. Erhvervsakadem'  
      8 = 'Mellemlang videregående uddannelse af 3-4 års varighed. Professionsbachelorer,'  
      9 = 'Universitetsbachelor. 1. del af kandidatuddannelse'  
      10 = 'Lang videregående uddannelse. Kandidatuddannelser af 5.-6. års varighed, F.eks'  
      11 = 'Licentiat'  
      12 = 'Forskeruddannelse. Ph.d., doktor'  
      13 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke' ;
   value V276F
      1 = 'Ansat'  
      2 = 'Selvstændig'  
      6 = 'Har aldrig haft et lønnet job'  
      8 = 'Ved ikke' ;
   value V278F
      1 = 'Ingen'  
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke' ;
   value V279F
      1 = 'Ja, gå til spm. 95'  
      2 = 'Nej, gå til spm. 96'  
      8 = 'Ved ikke' ;
   value V280F
      1 = '1-9'  
      2 = '10-24'  
      3 = '25 eller flere'  
      8 = 'Ved ikke' ;
   value V281F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V282F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V283F
      1 = 'Laveste indkomst decil'  
      2 = '2.'  
      3 = '3.'  
      4 = '4.'  
      5 = '5.'  
      6 = '6.'  
      7 = '7.'  
      8 = '8.'  
      9 = '9.'  
      10 = 'Højeste indkomst decil'  
      88 = 'Ved ikke' ;
   value V284F
      1 = '1.999 eller mindre'  
      2 = '2.000-2.999'  
      3 = '3.000-3.4999'  
      4 = '3.500-4.299'  
      5 = '4.300-5.199'  
      6 = '5.200-6.2999'  
      7 = '6.300-7.899'  
      8 = '7.900-9.899'  
      9 = '9.900-12.599'  
      10 = '12.600 eller mere'  
      88 = 'Ved ikke' ;
   value V285F
      1 = '8.699 eller mindre'  
      2 = '8.700-12.899'  
      3 = '12.900-15.299'  
      4 = '15.300-18.699'  
      5 = '18.700-22.499'  
      6 = '22.500-27.399'  
      7 = '27.400-34.199'  
      8 = '34.200-42.599'  
      9 = '42.700-54.599'  
      10 = '54.600 eller mere'  
      88 = 'Ved ikke' ;
   value V286F
      1 = '103.999 eller mindre'  
      2 = '104.000-154.999'  
      3 = '155.500-183.999'  
      4 = '184.000-224.000'  
      5 = '225.000-269.999'  
      6 = '270.000-328.999'  
      7 = '329.000-410.000'  
      8 = '411.000-512.999'  
      9 = '513.000-654.999'  
      10 = '655.000 eller mere'  
      88 = 'Ved ikke' ;
   value V287F
      1 = 'Ingen skolegang. Børnehaveklasse. 1.-5. klasse.'  
      2 = 'Folkeskole 6.-8. klasse'  
      3 = 'Folkeskole 9.-10. klasse'  
      4 = 'Gymnasielle uddannelser, studentereksamen, HF, HHX, HTX'  
      5 = 'Kort erhvervsuddannelse under 1-2 års varighed, F.eks. AMU Arbejdsmarkedsuddann'  
      6 = 'Faglig uddannelse (håndværk, handel, landbrug mv.), F.eks. Faglærte, Social-'  
      7 = 'Kort videregående uddannelse af op til 2-3 års varighed, F.eks. Erhvervsakadem'  
      8 = 'Mellemlang videregående uddannelse af 3-4 års varighed. Professionsbachelorer,'  
      9 = 'Universitetsbachelor. 1. del af kandidatuddannelse'  
      10 = 'Lang videregående uddannelse. Kandidatuddannelser af 5.-6. års varighed, F.eks'  
      11 = 'Licentiat'  
      12 = 'Forskeruddannelse. Ph.d., doktor'  
      13 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke' ;
   value V288F
      1 = 'Ingen skolegang. Børnehaveklasse. 1.-5. klasse.'  
      2 = 'Folkeskole 6.-8. klasse'  
      3 = 'Folkeskole 9.-10. klasse'  
      4 = 'Gymnasielle uddannelser, studentereksamen, HF, HHX, HTX'  
      5 = 'Kort erhvervsuddannelse under 1-2 års varighed, F.eks. AMU Arbejdsmarkedsuddann'  
      6 = 'Faglig uddannelse (håndværk, handel, landbrug mv.), F.eks. Faglærte, Social-'  
      7 = 'Kort videregående uddannelse af op til 2-3 års varighed, F.eks. Erhvervsakadem'  
      8 = 'Mellemlang videregående uddannelse af 3-4 års varighed. Professionsbachelorer,'  
      9 = 'Universitetsbachelor. 1. del af kandidatuddannelse'  
      10 = 'Lang videregående uddannelse. Kandidatuddannelser af 5.-6. års varighed, F.eks'  
      11 = 'Licentiat'  
      12 = 'Forskeruddannelse. Ph.d., doktor'  
      13 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke' ;
   value V289F
      1 = 'Ja lønmodtager'  
      2 = 'Ja, selvstændig'  
      3 = 'Andet'  
      8 = 'Ved ikke' ;
   value V290F
      1 = 'Ja lønmodtager'  
      2 = 'Ja, selvstændig'  
      3 = 'Andet'  
      8 = 'Ved ikke' ;
   value V291F
      1 = 'Liberale og tekniske erhverv (fx: læge, lærer, ingeniør, kunstner, revisor, s'  
      2 = 'Administration på højt niveau (fx: bankmedarbejder, direktør i stor virksomhe'  
      3 = 'Kontor (fx: sekretær, kontorassistent, kontorleder, embedsmand, bogholder)'  
      4 = 'Salg (fx: salgschef, butiksejer, butiksmedarbejder, forsikringsagent, indkøber)'  
      5 = 'Service (fx: restaurantejer, politibetjent, servitrice, barber, vicevært)'  
      6 = 'Faglært arbejder (fx: værkfører, automekaniker, tømmer, smed, værktøjsmage'  
      7 = 'Specialarbejder (fx: Svejser, vinduespoler, montør, støberiarbejder, mejeriarb'  
      8 = 'Ufaglært (fx: arbejdsmand, portner, ufaglært fabriksarbejder, rengøringsassis'  
      9 = 'Landarbejder (fx: landbrugsmedhjælper, traktorfører)'  
      10 = 'Landmand, leder af landbrugsbedrift'  
      88 = 'Ved ikke' ;
   value LABAE
      1 = 'I høj grad'  
      2 = 'I nogen grad'  
      3 = 'I mindre grad'  
      4 = 'Slet ikke'  
      8 = 'Ved ikke' ;
   value V300F
      1 = 'Byen København'  
      2 = 'Københavns omegn'  
      3 = 'Nordsjælland'  
      4 = 'Bornholm'  
      5 = 'Østsjælland'  
      6 = 'Vest- og Sydsjælland'  
      7 = 'Fyn'  
      8 = 'Sydjylland'  
      9 = 'Østjylland'  
      10 = 'Vestjylland'  
      11 = 'Nordjylland' ;
   value V301F
      1 = 'Færre end 2000'  
      2 = '2001-5000'  
      3 = '5001-10.000'  
      4 = '10.001-20.000'  
      5 = '20.001-50.000'  
      6 = '50.001-100.000'  
      7 = 'Flere end 100.000'  
      88 = 'Ved ikke' ;
   value V307F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Slet ikke interesseret'  
      8 = 'Nægter at svare' ;
   value V309F
      1 = 'Underklassen'  
      2 = 'Arbjderklassen'  
      3 = 'Lavere middelklassen'  
      4 = 'Middelklassen'  
      5 = 'Øvre middelklassen'  
      6 = 'Overklassen'  
      88 = 'Ved ikke' ;
   value LABAF
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value LABAG
      1 = 'Slet ikke attraktivt'  
      10 = 'Særdeles attraktivt'  
      88 = 'Ved ikke' ;
   value V322F
      1 = 'Amerikanere'  
      2 = 'Englændere'  
      3 = 'Finner'  
      4 = 'Franskmænd'  
      5 = 'Tyskere'  
      6 = 'Islændinge'  
      7 = 'Nordmænd'  
      8 = 'Russere'  
      9 = 'Svenskere'  
      10 = 'Andre'  
      11 = 'Ingen'  
      88 = 'Ved ikke' ;
   value V324F
      1 = 'Elementary school or unknown'  
      2 = 'Secondary education'  
      3 = 'Short-cycle tertiary eduation'  
      4 = 'Medium-cycle tertiary eduation'  
      5 = 'Long-cycle tertiary eduation, Ph.D' ;
   value V325F
      1 = '<150.0000'  
      2 = '150.000-250.000'  
      3 = '250.000-350.000'  
      4 = '350.000<' ;
   value V326F
      1 = 'Male'  
      2 = 'Female' ;
   value V329F
      1 = '18-26 år'  
      2 = '27-35 år'  
      3 = '36-44 år'  
      4 = '45-53 år'  
      5 = '54-62 år'  
      6 = '63-71år'  
      7 = '72år og ældre' ;
   value V330F
      1 = '1890-1898'  
      2 = '1899-1907'  
      3 = '1908-1916'  
      4 = '1917-1925'  
      5 = '1926-1934'  
      6 = '1935-1943'  
      7 = '1944-1952'  
      8 = '1953-1961'  
      9 = '1962-1970'  
      10 = '1971-1979'  
      11 = '1980-1988'  
      12 = '1989-1997'  
      13 = '1998-1999' ;
   value V331F
      1 = 'Gift eller reg. partnerskab'  
      2 = 'Papirløst partnerskab'  
      3 = 'Enke/enkemand'  
      4 = 'Skilt'  
      5 = 'Separeret'  
      6 = 'Enlig'  
      8 = 'Ved ikke' ;
   value V333F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Uoplyst/ved ikke' ;
   value V334F
      1 = 'Landområder og landsbyer'  
      2 = 'Mindre byer'  
      3 = 'Mellemstore byer'  
      4 = 'Større provinsbyer'  
      5 = 'De 3 store provinsbyer'  
      6 = 'Hovedstadsområdet'  
      88 = 'Ved ikke' ;
   value V335F
      1 = 'Grundskole og gym.'  
      2 = 'Erhvervsfaglige uddannelser'  
      3 = 'Korte vid. udd'  
      4 = 'Mellemlange vid. udd'  
      5 = 'Lang vid. udd' ;
   value V336F
      1 = 'Grundskole og gym.'  
      2 = 'Erhvervsfaglige uddannelser'  
      3 = 'Korte vid. udd'  
      4 = 'Mellemlange vid. udd'  
      5 = 'Lang vid. udd' ;
   value V337F
      1 = 'Grundskole og gym.'  
      2 = 'Erhvervsfaglige uddannelser'  
      3 = 'Korte vid. udd'  
      4 = 'Mellemlange vid. udd'  
      5 = 'Lang vid. udd' ;
   value V338F
      1 = 'Grundskole og gym.'  
      2 = 'Erhvervsfaglige uddannelser'  
      3 = 'Korte vid. udd'  
      4 = 'Mellemlange vid. udd'  
      5 = 'Lang vid. udd' ;
   value V339F
      1 = 'Ja, lønmodtager 30 timer om ugen eller mere'  
      2 = 'Ja, lønmodtager mindre end 30 timer om ugen'  
      3 = 'Ja, selvstændig'  
      4 = 'Nej, efterlønner el førtidspensionist el pensionist'  
      5 = 'Nej, hjemmegående'  
      6 = 'Nej, studerende'  
      7 = 'Nej, arbejdsløs'  
      8 = 'Nej, andet'  
      88 = 'Ved ikke' ;
   value V340F
      1 = 'Ja, lønmodtager 30 timer om ugen eller mere'  
      2 = 'Ja, lønmodtager mindre end 30 timer om ugen'  
      3 = 'Ja, selvstændig'  
      4 = 'Værnepligtig'  
      5 = 'Nej, efterlønner/førtidspensionist/pensionist'  
      6 = 'Nej, hjemmegående'  
      7 = 'Nej, studerende'  
      8 = 'Nej, arbejdsløs'  
      9 = 'Nej, handicappet'  
      10 = 'Nej, andet'  
      88 = 'Ved ikke' ;
   value V352F
      1 = 'Privat'  
      2 = 'Offentlig'  
      7 = 'Irrelevant'  
      8 = 'Ved ikke' ;
   value V354F
      1 = 'Socialdemokraterne'  
      2 = 'Det Radikale Venstre'  
      3 = 'Det Konservative Folkeparti'  
      4 = 'Socialistisk Folkeparti'  
      5 = 'Dansk Folkeparti'  
      6 = 'Kristendemokraterne'  
      7 = 'Venstre, Danmarks Liberale Parti'  
      8 = 'Liberal Alliance (tidl. Ny Alliance)'  
      9 = 'Enhedslisten m.fl.'  
      10 = 'CD'  
      11 = 'Fremskridtspartiet'  
      12 = 'Nye Borgerlige'  
      13 = 'Alternativet'  
      14 = 'Andre'  
      15 = 'Vil stemme blankt'  
      87 = 'Vil ikke stemme'  
      88 = 'Ved ikke'  
      89 = 'Har ikke stemmeret' ;
   value V355F
      0 = 'Ingen'  
      1 = '1'  
      2 = '2 eller flere' ;
   value V356F
      0 = 'Nej'  
      1 = 'Ja' ;
   value V357F
      1 = 'Mindst én gang om måneden'  
      2 = 'Til højtider'  
      3 = 'Ca. én gang om året'  
      4 = 'Aldrig eller næsten aldrig'  
      8 = 'Ved ikke' ;
   value V358F
      0 = 'Nej'  
      1 = 'Ja' ;
   value V359F
      1 = 'Materialister'  
      2 = 'Både-og'  
      3 = 'Postmaterialister'  
      8 = 'Ved ikke' ;

proc datasets library = library ;
modify u34642;
   format        V3 V3F.;
   format        V9 V9F.;
   format       V13 LABA.;
   format       V14 LABA.;
   format       V15 LABA.;
   format       V16 LABA.;
   format       V17 LABA.;
   format       V18 LABA.;
   format       V19 V19F.;
   format       V20 V20F.;
   format       V21 LABB.;
   format       V22 LABB.;
   format       V23 LABB.;
   format       V24 LABB.;
   format       V25 LABB.;
   format       V26 LABB.;
   format       V27 LABB.;
   format       V28 LABB.;
   format       V29 LABB.;
   format       V30 LABB.;
   format       V31 LABB.;
   format       V32 LABB.;
   format       V33 V33F.;
   format       V34 LABC.;
   format       V35 LABC.;
   format       V36 LABC.;
   format       V37 LABC.;
   format       V38 LABC.;
   format       V39 LABC.;
   format       V40 LABC.;
   format       V41 LABC.;
   format       V42 LABC.;
   format       V43 LABC.;
   format       V44 V44F.;
   format       V45 LABD.;
   format       V46 LABD.;
   format       V47 LABD.;
   format       V48 LABD.;
   format       V49 LABD.;
   format       V50 LABD.;
   format       V51 V51F.;
   format       V52 V52F.;
   format       V53 LABE.;
   format       V54 LABE.;
   format       V55 LABE.;
   format       V56 LABE.;
   format       V57 LABE.;
   format       V58 LABE.;
   format       V59 LABE.;
   format       V60 LABF.;
   format       V61 LABF.;
   format       V62 LABF.;
   format       V63 LABF.;
   format       V64 LABF.;
   format       V65 V65F.;
   format       V66 V66F.;
   format       V68 V68F.;
   format       V69 V69F.;
   format       V70 V70F.;
   format       V71 V71F.;
   format       V72 V72F.;
   format       V73 LABG.;
   format       V74 LABG.;
   format       V75 LABG.;
   format       V76 LABG.;
   format       V77 LABG.;
   format       V78 V78F.;
   format       V79 V79F.;
   format       V80 V80F.;
   format       V81 LABH.;
   format       V82 LABH.;
   format       V83 LABH.;
   format       V84 LABH.;
   format       V85 LABH.;
   format       V86 LABH.;
   format       V87 V87F.;
   format       V88 LABI.;
   format       V89 LABI.;
   format       V90 LABI.;
   format       V91 LABI.;
   format       V92 LABI.;
   format       V93 LABI.;
   format       V94 LABI.;
   format       V95 LABI.;
   format       V96 LABJ.;
   format       V97 LABK.;
   format       V98 LABJ.;
   format       V99 LABK.;
   format      V100 LABJ.;
   format      V101 LABJ.;
   format      V102 LABJ.;
   format      V103 LABL.;
   format      V104 LABL.;
   format      V105 LABL.;
   format      V106 LABL.;
   format      V107 LABL.;
   format      V108 LABL.;
   format      V109 LABL.;
   format      V110 LABL.;
   format      V111 LABL.;
   format      V112 LABL.;
   format      V113 LABL.;
   format      V114 LABL.;
   format      V115 V115F.;
   format      V116 LABM.;
   format      V117 LABM.;
   format      V118 LABM.;
   format      V119 LABM.;
   format      V120 V120F.;
   format      V121 V121F.;
   format      V122 V122F.;
   format      V123 V123F.;
   format      V124 V124F.;
   format      V125 V125F.;
   format      V126 LABN.;
   format      V127 LABN.;
   format      V128 LABO.;
   format      V129 LABO.;
   format      V130 V130F.;
   format      V131 LABP.;
   format      V132 LABP.;
   format      V133 LABQ.;
   format      V134 LABQ.;
   format      V135 LABQ.;
   format      V136 LABQ.;
   format      V137 LABQ.;
   format      V138 LABQ.;
   format      V139 LABQ.;
   format      V140 LABQ.;
   format      V141 LABQ.;
   format      V142 LABQ.;
   format      V143 LABQ.;
   format      V144 LABQ.;
   format      V145 LABQ.;
   format      V146 LABQ.;
   format      V147 LABQ.;
   format      V148 LABQ.;
   format      V149 LABQ.;
   format      V150 LABQ.;
   format      V151 V151F.;
   format      V152 V152F.;
   format      V153 V153F.;
   format      V154 V154F.;
   format      V155 V155F.;
   format      V156 V156F.;
   format      V157 V157F.;
   format      V158 V158F.;
   format      V159 V159F.;
   format      V160 V160F.;
   format      V161 V161F.;
   format      V162 V162F.;
   format      V163 LABR.;
   format      V164 LABR.;
   format      V165 LABR.;
   format      V166 LABR.;
   format      V167 LABS.;
   format      V168 LABS.;
   format      V169 LABS.;
   format      V170 LABS.;
   format      V171 LABS.;
   format      V172 LABS.;
   format      V173 LABS.;
   format      V174 LABS.;
   format      V175 LABS.;
   format      V176 LABS.;
   format      V177 LABS.;
   format      V178 LABS.;
   format      V179 LABS.;
   format      V180 LABS.;
   format      V181 LABS.;
   format      V182 LABT.;
   format      V183 LABT.;
   format      V184 LABT.;
   format      V185 LABT.;
   format      V186 LABT.;
   format      V187 V187F.;
   format      V188 V188F.;
   format      V189 LABU.;
   format      V190 LABU.;
   format      V191 LABU.;
   format      V192 V192F.;
   format      V193 V193F.;
   format      V194 LABV.;
   format      V195 LABV.;
   format      V196 LABV.;
   format      V197 LABV.;
   format      V198 LABV.;
   format      V199 LABV.;
   format      V200 LABV.;
   format      V201 LABV.;
   format      V202 V202F.;
   format      V203 V203F.;
   format      V204 V204F.;
   format      V205 V205F.;
   format      V206 V206F.;
   format      V207 LABW.;
   format      V208 LABW.;
   format      V209 LABW.;
   format      V210 LABW.;
   format      V211 LABW.;
   format      V212 LABW.;
   format      V213 LABW.;
   format      V214 LABW.;
   format      V215 LABW.;
   format      V216 V216F.;
   format      V217 LABX.;
   format      V218 LABX.;
   format      V219 LABX.;
   format      V220 LABX.;
   format      V221 LABX.;
   format      V222 V222F.;
   format      V223 LABY.;
   format      V224 LABY.;
   format      V225 LABY.;
   format      V226 LABZ.;
   format      V227 LABZ.;
   format      V228 LABZ.;
   format      V229 LABZ.;
   format      V230 LABAA.;
   format      V231 LABAA.;
   format      V232 LABAA.;
   format      V233 LABAA.;
   format      V234 LABAA.;
   format      V235 LABAA.;
   format      V236 LABAA.;
   format      V237 LABAA.;
   format      V238 LABAA.;
   format      V239 LABAB.;
   format      V240 LABAB.;
   format      V241 LABAB.;
   format      V242 LABAB.;
   format      V243 V243F.;
   format      V245 LABAC.;
   format      V248 LABAC.;
   format      V250 LABAC.;
   format      V252 V252F.;
   format      V253 LABAD.;
   format      V254 LABAD.;
   format      V255 LABAD.;
   format      V256 V256F.;
   format      V263 V263F.;
   format      V264 V264F.;
   format      V266 V266F.;
   format      V268 V268F.;
   format      V269 V269F.;
   format      V270 V270F.;
   format      V271 V271F.;
   format      V272 V272F.;
   format      V274 V274F.;
   format      V276 V276F.;
   format      V278 V278F.;
   format      V279 V279F.;
   format      V280 V280F.;
   format      V281 V281F.;
   format      V282 V282F.;
   format      V283 V283F.;
   format      V284 V284F.;
   format      V285 V285F.;
   format      V286 V286F.;
   format      V287 V287F.;
   format      V288 V288F.;
   format      V289 V289F.;
   format      V290 V290F.;
   format      V291 V291F.;
   format      V292 LABAE.;
   format      V293 LABAE.;
   format      V294 LABAE.;
   format      V295 LABAE.;
   format      V296 LABAE.;
   format      V297 LABAE.;
   format      V298 LABAE.;
   format      V299 LABAE.;
   format      V300 V300F.;
   format      V301 V301F.;
   format      V307 V307F.;
   format      V309 V309F.;
   format      V310 LABAF.;
   format      V311 LABAF.;
   format      V312 LABAF.;
   format      V313 LABAF.;
   format      V314 LABAF.;
   format      V315 LABAF.;
   format      V316 LABAF.;
   format      V317 LABAF.;
   format      V318 LABAF.;
   format      V319 LABAF.;
   format      V320 LABAG.;
   format      V321 LABAG.;
   format      V322 V322F.;
   format      V324 V324F.;
   format      V325 V325F.;
   format      V326 V326F.;
   format      V329 V329F.;
   format      V330 V330F.;
   format      V331 V331F.;
   format      V333 V333F.;
   format      V334 V334F.;
   format      V335 V335F.;
   format      V336 V336F.;
   format      V337 V337F.;
   format      V338 V338F.;
   format      V339 V339F.;
   format      V340 V340F.;
   format      V352 V352F.;
   format      V354 V354F.;
   format      V355 V355F.;
   format      V356 V356F.;
   format      V357 V357F.;
   format      V358 V358F.;
   format      V359 V359F.;
quit;
