/* This Proc Format program was automatically generated by Stat/Transfer ver.14.2.1138.0513 */



libname library '/home/Carsten/Skrivebord/' ;

proc format library = library ;
   value V7F
      1981 = '1981'  
      1990 = '1990'  
      1999 = '1999'  
      2008 = '2008' ;
   value V8F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V9F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V10F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V11F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V12F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V13F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørsgmålet er ikke stillet i 1981' ;
   value V14F
      1 = 'Ofte'  
      2 = 'Nu og da'  
      3 = 'Aldrig'  
      8 = 'Ved ikke' ;
   value V15F
      1 = 'Meget lykkelig'  
      2 = 'Ret lykkelig'  
      3 = 'Ikke særlig lykkelig'  
      4 = 'Slet ikke lykkelig'  
      8 = 'Ved ikke' ;
   value V16F
      1 = 'Meget godt'  
      2 = 'Godt'  
      3 = 'Nogenlunde'  
      4 = 'Dårligt'  
      5 = 'Meget dårligt'  
      8 = 'Ved ikke' ;
   value V17F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt, gå til spm. 6 (V48)'  
      8 = 'Ved ikke' ;
   value V18F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V19F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V20F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V21F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V22F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V23F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V24F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V25F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V26F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V27F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V28F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V29F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V30F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V31F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V32F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V33F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V34F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V35F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V36F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V37F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V38F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet ikke stillet i 1981' ;
   value V39F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V40F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V41F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V42F
      1 = 'Ja'  
      5 = 'Nej' ;
   value V43F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V44F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V45F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V46F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V47F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V48F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V49F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V50F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V51F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V52F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V53F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V54F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V55F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V56F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V57F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V58F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V59F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V60F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V61F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V62F
      1 = 'De fleste er til at stole på'  
      2 = 'Man kan ikke være for forsigtig'  
      8 = 'Ved ikke' ;
   value V63F
      1 = 'De fleste ville prøve at udnytte mig'  
      10 = 'De fleste ville behandle mig ordentligt'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V64F
      1 = 'Folk tænker mest på sig selv'  
      10 = 'Folk er for det meste hjælpsomme'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V65F
      1 = 'Overhovedet ingen indflydelse'  
      10 = 'Overordentlig megen indflydelse'  
      88 = 'Ved ikke' ;
   value V66F
      1 = 'Meget utilfreds'  
      10 = 'Meget tilfreds'  
      88 = 'Ved ikke' ;
   value V67F
      1 = 'Fordi de er uheldige'  
      2 = 'Fordi de er dovne og mangler viljestyrke'  
      3 = 'Fordi der er uretfærdighed i vort samfund'  
      4 = 'Det er et uundgåeligt resultat af den moderne udvikling'  
      5 = 'Ingen af disse grunde'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V68F
      1 = 'Fordi de er uheldige'  
      2 = 'Fordi de er dovne og mangler viljestyrke'  
      3 = 'Fordi der er uretfærdighed i vort samfund'  
      4 = 'Det er et uundgåeligt resultat af den moderne udvikling'  
      5 = 'Ingen af disse grunde'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V69F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V70F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V71F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V72F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V73F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V74F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V75F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V76F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V77F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V78F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V79F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V80F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V81F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V82F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V83F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V84F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V85F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V86F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V87F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V88F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V89F
      1 = 'Ja, gå til spm. 16 (V90)'  
      5 = 'Nej, gå til spm. 18 (V92)'  
      8 = 'Ved ikke, gå til spm. 18 (V92)' ;
   value V90F
      1 = 'Meget utilfreds'  
      10 = 'Meget tilfreds'  
      88 = 'Ved ikke' ;
   value V91F
      1 = 'Slet ingen frihed'  
      10 = 'Meget stor frihed'  
      88 = 'Ved ikke' ;
   value V92F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V93F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V94F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V95F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V96F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V97F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V98F
      1 = 'Meget vigtigt'  
      2 = 'Vigtigt'  
      3 = 'Ikke vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V99F
      1 = 'Meget vigtigt'  
      2 = 'Vigtigt'  
      3 = 'Ikke vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V100F
      1 = 'Meget vigtigt'  
      2 = 'Vigtigt'  
      3 = 'Ikke vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V101F
      1 = 'Meget vigtigt'  
      2 = 'Vigtigt'  
      3 = 'Ikke vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V102F
      1 = 'Man bør følge arbejdsinstruktionerne'  
      2 = 'Man må først være overbevist om, at disse er rigtige'  
      3 = 'Det kommer an på den konkrete situation'  
      8 = 'Ved ikke' ;
   value V103F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V104F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V105F
      1 = 'Mest enig i udsagn A'  
      2 = 'Mest enig i udsagn B'  
      3 = 'Mest enig i udsagn C'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V106F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 24 (V110)'  
      8 = 'Ved ikke' ;
   value V107F
      1 = 'Romersk katolsk'  
      2 = 'Den danske Folkekirke'  
      3 = 'Jehovas Vidne, adventist mv.'  
      4 = 'Jøde'  
      5 = 'Muslim'  
      6 = 'Hindu'  
      7 = 'Buddhist'  
      8 = 'Andet, skriv hvilket'  
      88 = 'Ved ikke' ;
   value V109F
      1 = 'Ja, gå til spm. 24.a (V111)'  
      5 = 'Nej, gå til spm. 25 (V113)'  
      8 = 'Ved ikke, gå til spm. 25 (V113)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V110F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 25 (V113)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V111F
      1 = 'Romersk katolsk'  
      2 = 'Den danske Folkekirke'  
      3 = 'Jehovas Vidne, adventist mv.'  
      4 = 'Jøde'  
      5 = 'Muslim'  
      6 = 'Hindu'  
      7 = 'Buddhist'  
      8 = 'Anden, skriv hvilket'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V113F
      1 = 'Oftere end 1 gang om ugen'  
      2 = 'Ca. 1 gang om ugen'  
      3 = 'Ca. 1 gang om måneden'  
      4 = 'Ved særlige højtider (herunder jul og påske)'  
      5 = 'Ca. 1 gang om året'  
      6 = 'Sjældnere end 1 gang om året'  
      7 = 'Aldrig, næsten aldrig'  
      8 = 'Ved ikke' ;
   value V114F
      1 = 'Oftere end 1 gang om ugen'  
      2 = 'Ca. 1 gang om ugen'  
      3 = 'Ca. 1 gang om måneden'  
      4 = 'Ved særlige højtider (herunder jul og påske)'  
      5 = 'Ca. 1 gang om året'  
      6 = 'Sjældnere end 1 gang om året'  
      7 = 'Aldrig, næsten aldrig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V115F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V116F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V117F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V118F
      1 = 'Et troende menneske'  
      2 = 'Et ikke troende menneske'  
      3 = 'Overbevist ateist'  
      8 = 'Ved ikke' ;
   value V119F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V120F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V121F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V122F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V123F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V124F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V125F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V126F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V127F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V128F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V129F
      1 = 'Der er en personlig Gud'  
      2 = 'Der er en særlig åndelig kraft'  
      3 = 'Jeg ved ikke, hvad jeg skal tro'  
      4 = 'Jeg tror ikke, der er nogen form for åndelig kraft eller personlig Gud'  
      8 = 'Ved ikke' ;
   value V130F
      1 = 'Slet ikke'  
      5 = 'I høj grad'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V131F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Ikke særlig interesseret'  
      4 = 'Overhovedet ikke interesseret'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V132F
      1 = 'A. Der er kun en sand religion'  
      2 = 'B. Der er kun en sand religion, men der kan også findes grundlæggende sandheder i visse andre religioner'  
      3 = 'C. Der er ingen sand religion, men alle store religioner indeholder grundlæggende sandheder'  
      4 = 'D. Der er ingen sandhed i nogen af de store religioner'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V133F
      1 = 'Slet ingen rolle'  
      10 = 'Meget stor rolle'  
      88 = 'Ved ikke' ;
   value V134F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V135F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke' ;
   value V136F
      1 = 'Hver dag'  
      2 = 'Mere end 1 gang om ugen'  
      3 = '1 gang om ugen'  
      4 = 'Mindst 1 gang om måneden'  
      5 = 'Flere gange om året'  
      6 = 'Sjældnere'  
      7 = 'Aldrig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V137F
      1 = 'Nej, slet ikke'  
      10 = 'Ja, helt sikkert'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V138F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V139F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V140F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V141F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V142F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V143F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V144F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V145F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V146F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V147F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V148F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V149F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke' ;
   value V150F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V151F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V152F
      1 = 'Enig'  
      2 = 'Uenig'  
      8 = 'Ved ikke' ;
   value V153F
      1 = 'Væsentligt at få børn'  
      2 = 'Ikke væsentligt'  
      8 = 'Ved ikke' ;
   value V154F
      1 = 'Enig'  
      2 = 'Uenig'  
      8 = 'Ved ikke' ;
   value V155F
      1 = 'Ja'  
      5 = 'Nej'  
      7 = 'Det kommer an på (Denne svarmulighed læses ikke op)'  
      8 = 'Ved ikke' ;
   value V156F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V157F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V158F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V159F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V160F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V161F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V162F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V163F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V164F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V165F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V166F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V167F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V168F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V169F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V170F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V171F
      1 = 'Mest enig i udsagn A'  
      2 = 'Mest enig i udsagn B'  
      8 = 'Ved ikke'  
      11 = 'Ingen af delene - kun svarmulighed i 1990 og 1999' ;
   value V172F
      1 = 'A. Det er forældrenes pligt at gøre alt, hvad der står i deres magt for deres børn, uanset om det skulle gå ud over'  
      2 = 'B. Forældre har også deres eget liv, og man kan ikke forlange, at de skal ofre deres egen trivsel for børnenes skyld'  
      8 = 'Ved ikke'  
      11 = 'Ingen af delene - kun svarmulighed i 1981, 1990 og 1999' ;
   value V173F
      1 = 'A. Voksne børn har pligt til at passe deres forældre, selv om det går ud over deres egen trivsel'  
      2 = 'B. Voksne børn har deres eget liv og skal ikke ofre deres egen trivsel for forældre- nes skyld'  
      3 = 'C. Ingen af dem (læses ikke op)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V174F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V175F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V176F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V177F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V178F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V179F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V180F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V181F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V182F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V183F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V184F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke' ;
   value V185F
      0 = 'Ikke nævnt'  
      1 = 'Nævnt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V186F
      1 = 'Tilhænger'  
      2 = 'Modstander'  
      8 = 'Ved ikke' ;
   value V187F
      1 = 'Tilhænger'  
      2 = 'Modstander'  
      8 = 'Ved ikke' ;
   value V188F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Ikke særlig interesseret'  
      4 = 'Slet ikke interesseret'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V189F
      1 = 'Har deltaget'  
      2 = 'Ville muligvis deltage'  
      3 = 'Ville aldrig deltage'  
      8 = 'Ved ikke' ;
   value V190F
      1 = 'Har deltaget'  
      2 = 'Ville muligvis deltage'  
      3 = 'Ville aldrig deltage'  
      8 = 'Ved ikke' ;
   value V191F
      1 = 'Har deltaget'  
      2 = 'Ville muligvis deltage'  
      3 = 'Ville aldrig deltage'  
      8 = 'Ved ikke' ;
   value V192F
      1 = 'Har deltaget'  
      2 = 'Ville muligvis deltage'  
      3 = 'Ville aldrig deltage'  
      8 = 'Ved ikke' ;
   value V193F
      1 = 'Har deltaget'  
      2 = 'Ville muligvis deltage'  
      3 = 'Ville aldrig deltage'  
      8 = 'Ved ikke' ;
   value V194F
      1 = 'Enig i udsagn A'  
      2 = 'Enig i udsagn B'  
      3 = 'Hverken enig i udsagn A eller B (læses ikke op)'  
      8 = 'Ved ikke' ;
   value V195F
      1 = 'Venstreorienteret'  
      10 = 'Højreorienteret'  
      88 = 'Ved ikke' ;
   value V196F
      1 = 'Det enkelte menneske burde have mere ansvar for at sørge for sig selv'  
      10 = 'Det offentlige burde have mere ansvar for at sikre, at der bliver sørget for alle'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V197F
      1 = 'Hvis arbejdsløse ikke tager det arbejde, de bliver tilbudt, bør de miste deres arbejdsløshedsunderstøttelse'  
      10 = 'Arbejdsløse børe have ret til at afslå et job, de ikke ønsker'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V198F
      1 = 'Konkurrence er sundt. Det stimulerer folk til at arbejde hårdt og udvikle nye ideer'  
      10 = 'Konkurrence er usundt. Det bringer det værste frem i mennesket'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V199F
      1 = 'Staten burde give større frihed til virksomhederne'  
      10 = 'Staten burde kontrollere virksomhederne mere effektivt'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V200F
      1 = 'Indkomsterne bør gøres mere lige'  
      10 = 'Det skal bedre kunne betale sig for den enkelte at gøre en indsats'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1999' ;
   value V201F
      1 = 'En større del af erhvervs- livet skal være privat ejet'  
      10 = 'En større del af erhvervs- livet skal være offentligt ejet'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1999' ;
   value V202F
      1 = 'A. Hele den måde, vores samfund er organiseret på, skal ændres radikalt gennem revolutionær aktion'  
      2 = 'B. Vores samfund skal forbedres gradvis gennem reformer'  
      3 = 'C. Vores nuværende samfund skal forsvares utrætteligt mod alle forandringer'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V203F
      1 = 'At opretholde lov og orden i landet'  
      2 = 'At lade folk bestemme mere i vigtige regeringsbeslutninger'  
      3 = 'At bekæmpe stigende priser'  
      4 = 'At beskytte ytringsfriheden'  
      8 = 'Ved ikke' ;
   value V204F
      1 = 'At opretholde lov og orden i landet'  
      2 = 'At lade folk bestemme mere i vigtige regeringsbeslutninger'  
      3 = 'At bekæmpe stigende priser'  
      4 = 'At beskytte ytringsfriheden'  
      8 = 'Ved ikke' ;
   value V205F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke' ;
   value V206F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke' ;
   value V207F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V208F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V209F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V210F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V211F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V212F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V213F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V214F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V215F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V216F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V217F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V218F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V219F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V220F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke' ;
   value V221F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1999' ;
   value V222F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V223F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V224F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen tillid'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1990 og 1999' ;
   value V225F
      1 = 'Meget tilfreds'  
      2 = 'Temmelig tilfreds'  
      3 = 'Ikke særligt tilfreds'  
      4 = 'Slet ikke tilfreds'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V226F
      1 = 'Meget dårligt'  
      10 = 'Meget godt'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V227F
      1 = 'Meget godt'  
      2 = 'Temmelig godt'  
      3 = 'Temmelig dårligt'  
      4 = 'Meget dårligt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet 1981 og 1990' ;
   value V228F
      1 = 'Meget godt'  
      2 = 'Temmelig godt'  
      3 = 'Temmelig dårligt'  
      4 = 'Meget dårligt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V229F
      1 = 'Meget godt'  
      2 = 'Temmelig godt'  
      3 = 'Temmelig dårligt'  
      4 = 'Meget dårligt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V230F
      1 = 'Meget godt'  
      2 = 'Temmelig godt'  
      3 = 'Temmelig dårligt'  
      4 = 'Meget dårligt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V231F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V232F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V233F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V234F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V235F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V236F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V237F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V238F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V239F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V240F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V241F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V242F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V243F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1990' ;
   value V244F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V245F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V246F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke' ;
   value V247F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V248F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V249F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V250F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1999' ;
   value V251F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørsgmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V252F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V253F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V254F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V255F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V256F
      1 = 'Den by eller det lokalområde jeg bor i'  
      2 = 'Den egn eller den landsdel jeg bor i'  
      3 = 'danmark'  
      4 = 'Europa'  
      5 = 'Verden'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V257F
      1 = 'Den by eller det lokalområde jeg bor i'  
      2 = 'Den egn eller den landsdel jeg bor i'  
      3 = 'danmark'  
      4 = 'Europa'  
      5 = 'Verden'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V258F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 73 (V260)'  
      8 = 'Ved ikke, gå til spm. 73 (V260)'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V259F
      1 = 'Meget stolt'  
      2 = 'Ret stolt'  
      3 = 'Ikke særlig stolt'  
      4 = 'Slet ikke stolt'  
      8 = 'Ved ikke' ;
   value V260F
      1 = 'Virkelig bange'  
      10 = 'Slet ikke bange'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V261F
      1 = 'Virkelig bange'  
      10 = 'Slet ikke bange'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V262F
      1 = 'Virkelig bange'  
      10 = 'Slet ikke bange'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V263F
      1 = 'Virkelig bange'  
      10 = 'Slet ikke bange'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V264F
      1 = 'Virkelig bange'  
      10 = 'Slet ikke bange'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V265F
      1 = 'Udvidelsen skal fortsætte'  
      10 = 'Udvidelsen er gået for vidt'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V266F
      1 = 'Ja, jeg ville stemme'  
      5 = 'Nej, jeg ville ikke stemme, gå til spm. 75b (V268)'  
      7 = 'Har ikke stemmeret, gå til spm. 76 (V269)'  
      8 = 'Ved ikke, gå til spm. 76 (V269)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V267F
      1 = 'Socialdemokraterne'  
      2 = 'Det Radikale Venstre'  
      3 = 'Det Konservative Folkeparti'  
      4 = 'Socialistisk Folkeparti'  
      5 = 'Dansk Folkeparti'  
      6 = 'Kristendemokraterne'  
      7 = 'Venstre, Danmarks Liberale Parti'  
      8 = 'Ny alliance'  
      9 = 'Enhedslisten m.fl.'  
      10 = 'cd'  
      11 = 'Fremskridtspartiet'  
      12 = 'Andre'  
      86 = 'Vil stemme blankt'  
      87 = 'Vil ikke stemme'  
      88 = 'Ved ikke'  
      89 = 'Har ikke stemmeret'  
      101 = 'Ingen data for 1981' ;
   value V268F
      1 = 'Socialdemokraterne'  
      2 = 'Det Radikale Venstre'  
      3 = 'Det Konservative Folkeparti'  
      4 = 'Socialistisk Folkeparti'  
      5 = 'Dansk Folkeparti'  
      6 = 'Kristendemokraterne'  
      7 = 'Venstre, Danmarks Liberale Parti'  
      8 = 'Ny alliance'  
      9 = 'Enhedslisten'  
      10 = 'Vil stemme blankt'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V269F
      1 = 'Lade alle der ønsker det komme ind i landet'  
      2 = 'Lade folk komme hertil så længe der er ledige jobs'  
      3 = 'Sætte grænser for hvor mange udlændinge der må komme ind i landet'  
      4 = 'Forbyde folk fra andre lande at komme ind i landet'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V270F
      1 = 'Mest enig i A'  
      2 = 'Mest enig i B'  
      3 = 'Hverken enig i A eller B (læses ikke op)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1990 og 1999' ;
   value V271F
      1 = 'Indvandrere tager jobs fra danskere'  
      10 = 'Indvandrere tager ikke jobs fra danskere'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V272F
      1 = 'Landets kultur bliver undergravet af indvandrere'  
      10 = 'Landets kultur bliver ikke undergravet af indvandrere'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V273F
      1 = 'Indvandrere gør problemerne med kriminalitet værre'  
      10 = 'Indvandrere gør ikke problemerne med kriminalitet værre'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V274F
      1 = 'Indvandrere belaster velfærds- systemet'  
      10 = 'Indvandrere belaster ikke velfærdssystemet'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V275F
      1 = 'I fremtiden bliver antallet af indvandrere en trussel mod samfundet'  
      10 = 'I fremtiden bliver antallet af indvandrere ikke nogen trussel mod samfundet'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V276F
      1 = 'Samfundet er bedst tjent med at indvandrere fastholder deres skikke og traditioner'  
      10 = 'Samfundet er bedst tjent med at indvandrere ikke fastholder deres skikke'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V277F
      1 = 'Helt enig'  
      2 = 'Stort set enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Stort set uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V278F
      1 = 'Helt enig'  
      2 = 'Stort set enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Stort set uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V279F
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V280F
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V281F
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V282F
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V283F
      1 = 'Meget vigtigt'  
      2 = 'Temmelig vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V284F
      1 = 'Hver dag'  
      2 = 'Flere gange om ugen'  
      3 = 'En eller to gange om ugen'  
      4 = 'Sjældnere'  
      5 = 'Aldrig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V285F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V286F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V287F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V288F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V289F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V290F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V291F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V292F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V293F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V294F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V295F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V296F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V297F
      1 = 'I høj grad'  
      2 = 'En hel del'  
      3 = 'Til en vis grad'  
      4 = 'Ikke særlig meget'  
      5 = 'Slet ikke'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V298F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V299F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V300F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V301F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V302F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V303F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V304F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V305F
      1 = 'Ofte'  
      2 = 'En gang imellem'  
      3 = 'Sjældent'  
      4 = 'Aldrig'  
      8 = 'Ved ikke' ;
   value V306F
      1 = 'Meget enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V307F
      1 = 'Meget enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V308F
      1 = 'Meget enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V309F
      1 = 'Meget enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V310F
      1 = 'Meget enig'  
      2 = 'Enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V311F
      1 = 'Mand'  
      5 = 'Kvinde' ;
   value V313F
      1 = 'Ja, gå til spm. 90 (V316)'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V316F
      1 = 'Ja, gå til spm. 93 (V320)'  
      5 = 'Nej'  
      8 = 'Ved ikke, gå til spm. 93 (V320)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V320F
      1 = 'Ja, gå til spm. 95 (V323)'  
      5 = 'Nej'  
      8 = 'Ved ikke, gå til spm. 95 (V323)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V323F
      1 = 'Ja, gå til spm. 97 (V326)'  
      5 = 'Nej'  
      8 = 'Ved ikke, gå spm. 97 (V326)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V326F
      1 = 'Gift/reg. partnerskab'  
      2 = 'Samlevende i papirløst ægteskab'  
      3 = 'Enke/Enkemand'  
      4 = 'Skilt'  
      5 = 'Separeret'  
      6 = 'Enlig'  
      8 = 'Ved ikke' ;
   value V327F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V328F
      1 = 'Ja, gå til filter 2'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V329F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet ikke stillet i 1981 og 1990' ;
   value V330F
      1 = 'Ja, gå til spm. 102 (V332)'  
      5 = 'Nej, gå til spm. 105 (V335)'  
      8 = 'Ved ikke, gå til spm. 105 (V335)'  
      9 = 'Uoplyst, gå til spm. 105 (V335)'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V331F
      1 = 'Ja, gå til spm. 104 (V334)'  
      5 = 'Nej, gå til spm. 105 (V335)'  
      8 = 'Ved ikke, gå til spm. 105 (V335)'  
      9 = 'Uoplyst, gå til spm. 105 (V335)'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V332F
      1 = 'Ja, var gift'  
      2 = 'Ja, havde registreret partnerskab'  
      5 = 'Nej, gå til spm. 104 (V334)'  
      8 = 'Ved ikke, gå til spm. 104 (V334)'  
      9 = 'Uoplyst, gå til spm. 104 (V334)'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V333F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V334F
      1 = 'På grund af separation/skilsmisse/ ophør af samliv'  
      2 = 'På grund af dødsfald'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet ikke stillet i 1981, 1990 og 1999' ;
   value V335F
      0 = 'Ingen børn'  
      1 = '1 barn'  
      2 = '2 børn'  
      3 = '3 børn'  
      4 = '4 børn'  
      5 = '5 børn'  
      6 = '6 børn eller flere' ;
   value V337F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V338F
      1 = '1 partner'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V339F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V340F
      1 = '1 barn'  
      2 = '2 børn'  
      3 = '3 børn'  
      4 = '4 børn'  
      5 = '5 børn'  
      6 = '6 børn'  
      7 = '7 børn'  
      8 = '8 børn'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V341F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V342F
      1 = '1 forælder'  
      2 = '2 forældre'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V343F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V344F
      1 = '1 bedsteforælder'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V345F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V346F
      1 = '1 andet familiemedlem'  
      2 = '2 andre familiemedlemmer'  
      3 = '3 andre familiemedlemmer'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V347F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V348F
      1 = '1 anden'  
      2 = '2 andre'  
      3 = '3 andre'  
      4 = '4 andre'  
      5 = '5 andre'  
      6 = '6 andre'  
      7 = '7 andre'  
      8 = '8 andre'  
      9 = '9 andre'  
      10 = '10 andre'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V349F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V351F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V353F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V355F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V357F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V359F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V362F
      1 = 'Går i skole'  
      2 = '7. klasse eller mindre'  
      3 = '8. klasse + mellemskole uden eksamen'  
      4 = '9. klasse statskontrolleret prøve og folkeskolens afgangs- prøver'  
      5 = 'Teknisk forberedelseseksamen'  
      6 = '10. klasses statskontrolleret prøve og folkeskolens udvidede afgangsprøver'  
      7 = 'Udvidet teknisk forberedelses- eksamen'  
      8 = '1. real'  
      9 = '2. real'  
      10 = '3. real uden eksamen'  
      11 = 'Realkurser uden eksamen'  
      12 = 'Mellemskoleeksamen'  
      13 = 'Real-, pigeskole- og præliminæreksamen'  
      14 = 'Gymnasium eller HF uden eksamen'  
      15 = 'Studenter- eller HF-eksamen'  
      16 = 'Andet (herunder udenlandsk skole)'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V363F
      1 = 'Ja, har én eller flere'  
      2 = 'Ja, er i gang med at få én'  
      5 = 'Nej, gå til spm. 111 (V366)'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V364F
      1 = 'Specialarbejderkursus'  
      2 = 'Faglig uddannelse (lærling, EFG f.eks. kontorassistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse'  
      4 = 'Handelshøjskole (korrespondent, HA, HD) eller Bankuddannelse'  
      5 = '2-3 årig teknisk uddannelse (f.eks. laborant, teknisk assistent, apoteksassistent, tandpleje)'  
      6 = 'Videregående teknisk uddannelse, evt. efter gennemført faglig uddannelse (f.eks. maskin eller byg- getekniker, bygning'  
      7 = '1-årig uddannelse indenfor social- eller sundhedsvæsenet (f.eks. syge- hjælper, beskæftigelsesvejleder)'  
      8 = '3-4 årig uddannelse indenfor social- og sundhedsvæsenet (f.eks. sygeplej- erske, plejeassistent)'  
      9 = '3-4 årig uddannelse indenfor under- visning og oplysning (f.eks. børnehave- /fritidspædagog, folkeskolelærer, biblio'  
      10 = 'Kandidat fra universitetet eller højere læreanstalt (f.eks. gymnasielærer, civil- ingeniør, tandlæge, advokat)'  
      11 = 'Uddannet indenfor forsvar, politi, post- væsenet, Toldvæsenet, Fængselsvæsnet mv.'  
      12 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V366F
      1 = 'Ja, lønmodtager 30 timer om ugen eller mere, gå til spm. 112 (V369)'  
      2 = 'Ja, lønmodtager mindre end 30 timer, gå til spm. 112 (V369)'  
      3 = 'Ja, selvstændig, gå til spm. 112 (V369)'  
      4 = 'Nej, efterlønsmodtager eller førtidspensionist eller pensionist'  
      5 = 'Nej, hjemmegående'  
      6 = 'Nej, studerende'  
      7 = 'Nej, arbejdsløs'  
      8 = 'Nej, andet' ;
   value V368F
      1 = 'Lønmodtager'  
      2 = 'Selvstændig'  
      7 = 'Har aldrig haft et job, gå til filter 4 (V376)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V371F
      1 = 'Ingen'  
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V372F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 114.dk.1 (V374)'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V373F
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller mere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1990' ;
   value V375F
      1 = 'Privat sektor'  
      2 = 'Staten'  
      3 = 'Region/Amt'  
      4 = 'Kommune'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V376F
      1 = 'Ja, gå til spm. 116 (V379)'  
      5 = 'Nej'  
      8 = 'Ved ikke, gå til spm. 116 (V379)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V379F
      1 = 'Går i skole'  
      2 = '7. klasse eller mindre'  
      3 = '8. klasse + mellemskole uden eksamen'  
      4 = '9. klasse statskontrolleret prøve og folkeskolens afgangsprøver'  
      5 = 'Teknisk forberedelseseksamen'  
      6 = '10. klasses statskontrolleret prøve og folkeskolens udvidede afgangsprøver'  
      7 = 'Udvidet teknisk forberedelseseksamen'  
      8 = '1. real'  
      9 = '2. real'  
      10 = '3. real uden eksamen'  
      11 = 'Realkurser uden eksamen'  
      12 = 'Mellemskoleeksamen'  
      13 = 'Real-, pigeskole- og præliminær- eksamen'  
      14 = 'Gymnasium eller HF uden eksamen'  
      15 = 'Studenter- eller HF-eksamen'  
      16 = 'Andet (herunder udenlandsk skole)'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981. 1990 og 1999' ;
   value V380F
      0 = 'Ingen'  
      1 = 'Specialarbejderkursus'  
      2 = 'Faglig uddannelse (lærling, EFG f.eks. kontorassistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse'  
      4 = 'Handelshøjskole (korrespondent, HA, HD) eller bankuddannelse'  
      5 = '2-3 årig teknisk uddannelse (f.eks. laborant, tekniskassistent, apoteksassistent, tandpleje)'  
      6 = 'Videregående teknisk uddannelse, evt. efter gennemført faglig ud- dannelse (f.eks. maskin eller byg- getekniker, bygni'  
      7 = '1-årig uddannelse indenfor social- eller sundhedsvæsenet (f.eks. syge- hjælper, beskæftigelsesvejleder)'  
      8 = '3-4 årig uddannelse indenfor social- og sundhedsvæsenet (f.eks. sygeple- jerske, plejeassistent)'  
      9 = '3-4 årig uddannelse indenfor under- visning og oplysning (f.eks. børnehave- /fritidspædagog, folkeskolelærer, bib- l'  
      10 = 'Kandidat fra universitetet eller højere læreanstalt (f.eks. gymnasielærer, civilingeniør, tandlæge, advokat)'  
      11 = 'Uddannet indenfor forsvar, politi, postvæsenet, toldvæsenet mv.'  
      12 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V382F
      1 = 'Ja, lønmodtager 30 timer om ugen eller mere, gå til spm. 118 (V385)'  
      2 = 'Ja, lønmodtager mindre end 30 timer, gå til spm. 118 (V385)'  
      3 = 'Ja, selvstændig, gå til spm. 118 (V385)'  
      4 = 'Nej, er værnepligtig'  
      5 = 'Nej, efterlønner/førtids- pensionist/pensionist'  
      6 = 'Nej, hjemmegående'  
      7 = 'Nej, studerende'  
      8 = 'Nej, arbejdsløs'  
      9 = 'Nej, handicappet'  
      10 = 'Nej, andet, hvilket:'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V384F
      1 = 'Lønmodtager'  
      2 = 'Selvstændig'  
      7 = 'Har aldrig haft et job, gå til spm. 121 (V392)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V388F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 120.dk.1 (V390)'  
      8 = 'Ved ikke, gå til spm. 120.dk.1 (V390)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V389F
      1 = '1-9'  
      2 = '10-24'  
      3 = '25 eller mere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V391F
      1 = 'Privat sektor'  
      2 = 'Staten'  
      3 = 'Region'  
      4 = 'Kommune'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V392F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V393F
      1 = 'A. Ja'  
      5 = 'B. Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V394F
      1 = 'Ja'  
      5 = 'Nej'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V395F
      1 = 'Ja'  
      5 = 'Nej'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V399F
      1 = 'Boede med en far og en mor'  
      2 = 'Boede kun med mor'  
      3 = 'Boede kun med far'  
      4 = 'Andet, gå til spm. 133 (V426)'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V400F
      1 = 'Gik i skole'  
      2 = '7. klasse eller mindre'  
      3 = '8. klasse + mellemskole uden eksamen'  
      4 = '9. klasse statskontrolleret prøve og folkeskolens afgangsprøver'  
      5 = 'Teknisk forberedelseseksamen'  
      6 = '10. klasses statskontrolleret prøve og folkeskolens udvidede afgangs- prøver'  
      7 = 'Udvidet teknisk forberedelseseksamen'  
      8 = '1. real'  
      9 = '2. real'  
      10 = '3. real uden eksamen'  
      11 = 'Realkurser uden eksamen'  
      12 = 'Mellemskoleeksamen'  
      13 = 'Real-, pigeskole- og præliminær- eksamen'  
      14 = 'Gymnasium eller HF uden eksamen'  
      15 = 'Studenter- eller HF-eksamen'  
      16 = 'Andet (herunder udenlandsk skole)'  
      17 = 'Mor død og/eller der var ingen i mor-rollen, gå til spm. 131.dk.3 (V409)'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V401F
      0 = 'Ingen erhvervsuddannelse'  
      1 = 'Specialarbejderkursus'  
      2 = 'Faglig uddannelse (lærling, EFG f.eks. kontorassistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse'  
      4 = 'Handelshøjskole (korrespondent, HA, HD) eller bankuddannelse'  
      5 = '2-3 årig teknisk uddannelse (f.eks. laborant, teknisk assistent, apoteksassistent, tandpleje)'  
      6 = 'Videregående teknisk uddannelse, evt. efter gennemført faglig uddannelse (f.eks. maskin eller byg- getekniker, bygning'  
      7 = '1-årig uddannelse indenfor social- eller sundhedsvæsenet (f.eks. syge- hjælper, beskæftigelsesvejleder)'  
      8 = '3-4 årig uddannelse indenfor social- og sundhedsvæsenet (f.eks. sygeplejerske, plejeassistent)'  
      9 = '3-4 årig uddannelse indenfor undervisning og oplysning (f.eks. børnehave-/fritids- pædagog, folkeskolelærer, bibliot'  
      10 = 'Kandidat fra universitetet eller højere læreanstalt (f.eks. gymnasielærer, civil- ingeniør, tandlæge, advokat)'  
      11 = 'Uddannet indenfor forsvar, politi, post- væsenet, toldvæsenet mv.'  
      12 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V403F
      1 = 'Ansat som lønmodtager'  
      2 = 'Arbejde som selvstændig'  
      3 = 'Hun havde ikke arbejde, gå til spm. 131.dk.3 (V409)'  
      7 = 'Mor død og/eller der var ingen i mor-rollen, gå til spm. 131.dk.3 (V409)'  
      8 = 'Ved ikke, gå til spm. 131.dk.3 (V409)'  
      11 = 'Spørgsmålet er ikke stillet i 1981, 1990 og 1999' ;
   value V406F
      1 = 'Ingen'  
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V407F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 131.dk.3 (V409)'  
      8 = 'Ved ikke, gå til spm. 131.dk.3 (V409)'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V408F
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V409F
      1 = 'Gik i skole'  
      2 = '7. klasse eller mindre'  
      3 = '8. klasse + mellemskole uden eksamen'  
      4 = '9. klasse statskontrolleret prøve og folkeskolens afgangsprøve'  
      5 = 'Teknisk forberedelseseksamen'  
      6 = '10. klasses statskontrolleret prøve og folkeskolens udvidede afgangsprøver'  
      7 = 'Udvidet teknisk forberedelseseksamen'  
      8 = '1. real'  
      9 = '2. real'  
      10 = '3. real uden eksamen'  
      11 = 'Realkurser uden eksamen'  
      12 = 'Mellemskoleeksamen'  
      13 = 'Real-, pigeskole- og præliminæreksamen'  
      14 = 'Gymnasium eller HF uden eksamen'  
      15 = 'Studenter- eller HF-eksamen'  
      16 = 'Andet (herunder udenlandsk skole)'  
      17 = 'Far død/ukendt og/eller der var ingen i far-rollen, gå til spm. 132 (V418)'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V410F
      0 = 'Ingen erhvervsuddannelse'  
      1 = 'Specialarbejderkursus'  
      2 = 'Faglig uddannelse (lærling, EFG f.eks. kontorassistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse'  
      4 = 'Handelshøjskole (korrespondent, HA, HD) eller bankuddannelse'  
      5 = '2-3 årig teknisk uddannelse (f.eks. laborant, teknisk assistent, apoteksassistent, tandpleje)'  
      6 = 'Videregående teknisk uddannelse, evt. efter gennemført faglig uddannelse (f.eks. maskin eller byg- getekniker, bygning'  
      7 = '1-årig uddannelse indenfor social- eller sundhedsvæsenet (f.eks. syge- hjælper, beskæftigelsesvejleder)'  
      8 = '3-4 årig uddannelse indenfor social- og sundhedsvæsenet (f.eks. sygeplejerske, plejeassistent)'  
      9 = '3-4 årig uddannelse indenfor undervis- ning og oplysning (f.eks. børnehave-/ fritidspædagog, folkeskolelærer, biblio'  
      10 = 'Kandidat fra universitetet eller højere læreanstalt (f.eks. gymnasielærer, civilingeniør, tandlæge, advokat)'  
      11 = 'Uddannet indenfor forsvar, politi, postvæsenet, toldvæsenet mv.'  
      12 = 'Anden uddannelse, hvilken:'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmål ikke stillet i 1981' ;
   value V412F
      1 = 'Ansat som lønmodtager'  
      2 = 'Arbejde som selvstændig'  
      3 = 'Han havde ikke arbejde, gå til spm. 132 (V418)'  
      7 = 'Far død/ukendt og/eller der var ingen i far-rollen, gå til spm. 132 (V418)'  
      8 = 'Ved ikke, gå til spm. 132 (V418)'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V415F
      1 = 'Ingen'  
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V416F
      1 = 'Ja'  
      5 = 'Nej, gå til spm. 132 (V418)'  
      8 = 'Ved ikke, gå til spm. 132 (V418)'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V417F
      2 = '1-9'  
      3 = '10-24'  
      4 = '25 eller flere'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V418F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V419F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V420F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V421F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V422F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V423F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V424F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V425F
      1 = 'I høj grad'  
      2 = 'Til en vis grad'  
      3 = 'En lille smule'  
      4 = 'Slet ikke'  
      7 = 'Irrelevant (Der var ingen i forældrerollen - mor/far død)'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmål ikke stillet i 1981, 1990 og 1999' ;
   value V428F
      1 = 'Færre end 2.000'  
      2 = '2.001-5.000'  
      3 = '5.001-10.000'  
      4 = '10.001-20.000'  
      5 = '20.001-50.000'  
      6 = '50.001-100.000'  
      7 = 'Flere end 100.000'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V429F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Slet ikke interesseret'  
      11 = 'Spørgsmålet er ikke stillet i 1981 og 1999' ;
   value V431F
      1 = 'Københavns Amt'  
      2 = 'Roskilde Amt'  
      3 = 'Frederiksborg Amt'  
      4 = 'Vestsjællands Amt'  
      5 = 'Storstrøms Amt'  
      6 = 'Fyns Amt'  
      7 = 'Nordjyllands Amt'  
      8 = 'Viborg Amt'  
      9 = 'Ringkøbing Amt'  
      10 = 'Århus Amt'  
      11 = 'Vejle Amt'  
      12 = 'Ribe/Sønderjyllands Amt'  
      14 = 'Bornholms Amt'  
      99 = 'Københavns og Frederiksberg kommuner' ;
   value V432F
      1 = 'Laveste tredjedel'  
      2 = 'Mellemste tredjedel'  
      3 = 'Øverste tredjedel'  
      8 = 'Ved ikke' ;
   value V433F
      1 = 'Grundskole'  
      2 = 'Erhvervsfaglig'  
      3 = 'Kort videregående'  
      4 = 'Mellem videregående'  
      5 = 'Lang videregående'  
      8 = 'Ved ikke'  
      11 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V435F
      1 = '18-29 år'  
      2 = '30-39 år'  
      3 = '40-49 år'  
      4 = '50-59 år'  
      5 = '60-69 år'  
      6 = '70 år +' ;
   value V436F
      1 = 'Før 1909'  
      2 = '1910 til 1918'  
      3 = '1919 til 1927'  
      4 = '1928 til 1936'  
      5 = '1937 til 1945'  
      6 = '1946 til 1954'  
      7 = '1955 til 1963'  
      8 = '1964 til 1972'  
      9 = '1973 til 1981'  
      10 = '1982 til 1990' ;
   value V437F
      1 = 'Landområder og landsbyer'  
      2 = 'Mindre byer'  
      3 = 'Mellemstore byer'  
      4 = 'Større provinsbyer'  
      5 = 'De 3 store provinsbyer'  
      88 = 'Ved ikke'  
      101 = 'Spørgsmålet er ikke stillet i 1981' ;
   value V438F
      1 = 'Center'  
      2 = 'Midt imellem'  
      3 = 'Periferi' ;
   value V439F
      1 = 'Mindst en gang om måneden'  
      2 = 'Til højtider'  
      3 = 'Ca. en gang om året'  
      4 = 'Aldrig eller næsten aldrig'  
      88 = 'Ved ikke' ;
   value V440F
      1 = 'Materialister'  
      2 = 'Både og'  
      3 = 'Postmaterialister'  
      8 = 'Ved ikke' ;
   value V441F
      0 = 'Ingen'  
      1 = '1'  
      2 = '2 eller flere' ;

proc datasets library = library ;
modify data23923;
   format        V7 V7F.;
   format        V8 V8F.;
   format        V9 V9F.;
   format       V10 V10F.;
   format       V11 V11F.;
   format       V12 V12F.;
   format       V13 V13F.;
   format       V14 V14F.;
   format       V15 V15F.;
   format       V16 V16F.;
   format       V17 V17F.;
   format       V18 V18F.;
   format       V19 V19F.;
   format       V20 V20F.;
   format       V21 V21F.;
   format       V22 V22F.;
   format       V23 V23F.;
   format       V24 V24F.;
   format       V25 V25F.;
   format       V26 V26F.;
   format       V27 V27F.;
   format       V28 V28F.;
   format       V29 V29F.;
   format       V30 V30F.;
   format       V31 V31F.;
   format       V32 V32F.;
   format       V33 V33F.;
   format       V34 V34F.;
   format       V35 V35F.;
   format       V36 V36F.;
   format       V37 V37F.;
   format       V38 V38F.;
   format       V39 V39F.;
   format       V40 V40F.;
   format       V41 V41F.;
   format       V42 V42F.;
   format       V43 V43F.;
   format       V44 V44F.;
   format       V45 V45F.;
   format       V46 V46F.;
   format       V47 V47F.;
   format       V48 V48F.;
   format       V49 V49F.;
   format       V50 V50F.;
   format       V51 V51F.;
   format       V52 V52F.;
   format       V53 V53F.;
   format       V54 V54F.;
   format       V55 V55F.;
   format       V56 V56F.;
   format       V57 V57F.;
   format       V58 V58F.;
   format       V59 V59F.;
   format       V60 V60F.;
   format       V61 V61F.;
   format       V62 V62F.;
   format       V63 V63F.;
   format       V64 V64F.;
   format       V65 V65F.;
   format       V66 V66F.;
   format       V67 V67F.;
   format       V68 V68F.;
   format       V69 V69F.;
   format       V70 V70F.;
   format       V71 V71F.;
   format       V72 V72F.;
   format       V73 V73F.;
   format       V74 V74F.;
   format       V75 V75F.;
   format       V76 V76F.;
   format       V77 V77F.;
   format       V78 V78F.;
   format       V79 V79F.;
   format       V80 V80F.;
   format       V81 V81F.;
   format       V82 V82F.;
   format       V83 V83F.;
   format       V84 V84F.;
   format       V85 V85F.;
   format       V86 V86F.;
   format       V87 V87F.;
   format       V88 V88F.;
   format       V89 V89F.;
   format       V90 V90F.;
   format       V91 V91F.;
   format       V92 V92F.;
   format       V93 V93F.;
   format       V94 V94F.;
   format       V95 V95F.;
   format       V96 V96F.;
   format       V97 V97F.;
   format       V98 V98F.;
   format       V99 V99F.;
   format      V100 V100F.;
   format      V101 V101F.;
   format      V102 V102F.;
   format      V103 V103F.;
   format      V104 V104F.;
   format      V105 V105F.;
   format      V106 V106F.;
   format      V107 V107F.;
   format      V109 V109F.;
   format      V110 V110F.;
   format      V111 V111F.;
   format      V113 V113F.;
   format      V114 V114F.;
   format      V115 V115F.;
   format      V116 V116F.;
   format      V117 V117F.;
   format      V118 V118F.;
   format      V119 V119F.;
   format      V120 V120F.;
   format      V121 V121F.;
   format      V122 V122F.;
   format      V123 V123F.;
   format      V124 V124F.;
   format      V125 V125F.;
   format      V126 V126F.;
   format      V127 V127F.;
   format      V128 V128F.;
   format      V129 V129F.;
   format      V130 V130F.;
   format      V131 V131F.;
   format      V132 V132F.;
   format      V133 V133F.;
   format      V134 V134F.;
   format      V135 V135F.;
   format      V136 V136F.;
   format      V137 V137F.;
   format      V138 V138F.;
   format      V139 V139F.;
   format      V140 V140F.;
   format      V141 V141F.;
   format      V142 V142F.;
   format      V143 V143F.;
   format      V144 V144F.;
   format      V145 V145F.;
   format      V146 V146F.;
   format      V147 V147F.;
   format      V148 V148F.;
   format      V149 V149F.;
   format      V150 V150F.;
   format      V151 V151F.;
   format      V152 V152F.;
   format      V153 V153F.;
   format      V154 V154F.;
   format      V155 V155F.;
   format      V156 V156F.;
   format      V157 V157F.;
   format      V158 V158F.;
   format      V159 V159F.;
   format      V160 V160F.;
   format      V161 V161F.;
   format      V162 V162F.;
   format      V163 V163F.;
   format      V164 V164F.;
   format      V165 V165F.;
   format      V166 V166F.;
   format      V167 V167F.;
   format      V168 V168F.;
   format      V169 V169F.;
   format      V170 V170F.;
   format      V171 V171F.;
   format      V172 V172F.;
   format      V173 V173F.;
   format      V174 V174F.;
   format      V175 V175F.;
   format      V176 V176F.;
   format      V177 V177F.;
   format      V178 V178F.;
   format      V179 V179F.;
   format      V180 V180F.;
   format      V181 V181F.;
   format      V182 V182F.;
   format      V183 V183F.;
   format      V184 V184F.;
   format      V185 V185F.;
   format      V186 V186F.;
   format      V187 V187F.;
   format      V188 V188F.;
   format      V189 V189F.;
   format      V190 V190F.;
   format      V191 V191F.;
   format      V192 V192F.;
   format      V193 V193F.;
   format      V194 V194F.;
   format      V195 V195F.;
   format      V196 V196F.;
   format      V197 V197F.;
   format      V198 V198F.;
   format      V199 V199F.;
   format      V200 V200F.;
   format      V201 V201F.;
   format      V202 V202F.;
   format      V203 V203F.;
   format      V204 V204F.;
   format      V205 V205F.;
   format      V206 V206F.;
   format      V207 V207F.;
   format      V208 V208F.;
   format      V209 V209F.;
   format      V210 V210F.;
   format      V211 V211F.;
   format      V212 V212F.;
   format      V213 V213F.;
   format      V214 V214F.;
   format      V215 V215F.;
   format      V216 V216F.;
   format      V217 V217F.;
   format      V218 V218F.;
   format      V219 V219F.;
   format      V220 V220F.;
   format      V221 V221F.;
   format      V222 V222F.;
   format      V223 V223F.;
   format      V224 V224F.;
   format      V225 V225F.;
   format      V226 V226F.;
   format      V227 V227F.;
   format      V228 V228F.;
   format      V229 V229F.;
   format      V230 V230F.;
   format      V231 V231F.;
   format      V232 V232F.;
   format      V233 V233F.;
   format      V234 V234F.;
   format      V235 V235F.;
   format      V236 V236F.;
   format      V237 V237F.;
   format      V238 V238F.;
   format      V239 V239F.;
   format      V240 V240F.;
   format      V241 V241F.;
   format      V242 V242F.;
   format      V243 V243F.;
   format      V244 V244F.;
   format      V245 V245F.;
   format      V246 V246F.;
   format      V247 V247F.;
   format      V248 V248F.;
   format      V249 V249F.;
   format      V250 V250F.;
   format      V251 V251F.;
   format      V252 V252F.;
   format      V253 V253F.;
   format      V254 V254F.;
   format      V255 V255F.;
   format      V256 V256F.;
   format      V257 V257F.;
   format      V258 V258F.;
   format      V259 V259F.;
   format      V260 V260F.;
   format      V261 V261F.;
   format      V262 V262F.;
   format      V263 V263F.;
   format      V264 V264F.;
   format      V265 V265F.;
   format      V266 V266F.;
   format      V267 V267F.;
   format      V268 V268F.;
   format      V269 V269F.;
   format      V270 V270F.;
   format      V271 V271F.;
   format      V272 V272F.;
   format      V273 V273F.;
   format      V274 V274F.;
   format      V275 V275F.;
   format      V276 V276F.;
   format      V277 V277F.;
   format      V278 V278F.;
   format      V279 V279F.;
   format      V280 V280F.;
   format      V281 V281F.;
   format      V282 V282F.;
   format      V283 V283F.;
   format      V284 V284F.;
   format      V285 V285F.;
   format      V286 V286F.;
   format      V287 V287F.;
   format      V288 V288F.;
   format      V289 V289F.;
   format      V290 V290F.;
   format      V291 V291F.;
   format      V292 V292F.;
   format      V293 V293F.;
   format      V294 V294F.;
   format      V295 V295F.;
   format      V296 V296F.;
   format      V297 V297F.;
   format      V298 V298F.;
   format      V299 V299F.;
   format      V300 V300F.;
   format      V301 V301F.;
   format      V302 V302F.;
   format      V303 V303F.;
   format      V304 V304F.;
   format      V305 V305F.;
   format      V306 V306F.;
   format      V307 V307F.;
   format      V308 V308F.;
   format      V309 V309F.;
   format      V310 V310F.;
   format      V311 V311F.;
   format      V313 V313F.;
   format      V316 V316F.;
   format      V320 V320F.;
   format      V323 V323F.;
   format      V326 V326F.;
   format      V327 V327F.;
   format      V328 V328F.;
   format      V329 V329F.;
   format      V330 V330F.;
   format      V331 V331F.;
   format      V332 V332F.;
   format      V333 V333F.;
   format      V334 V334F.;
   format      V335 V335F.;
   format      V337 V337F.;
   format      V338 V338F.;
   format      V339 V339F.;
   format      V340 V340F.;
   format      V341 V341F.;
   format      V342 V342F.;
   format      V343 V343F.;
   format      V344 V344F.;
   format      V345 V345F.;
   format      V346 V346F.;
   format      V347 V347F.;
   format      V348 V348F.;
   format      V349 V349F.;
   format      V351 V351F.;
   format      V353 V353F.;
   format      V355 V355F.;
   format      V357 V357F.;
   format      V359 V359F.;
   format      V362 V362F.;
   format      V363 V363F.;
   format      V364 V364F.;
   format      V366 V366F.;
   format      V368 V368F.;
   format      V371 V371F.;
   format      V372 V372F.;
   format      V373 V373F.;
   format      V375 V375F.;
   format      V376 V376F.;
   format      V379 V379F.;
   format      V380 V380F.;
   format      V382 V382F.;
   format      V384 V384F.;
   format      V388 V388F.;
   format      V389 V389F.;
   format      V391 V391F.;
   format      V392 V392F.;
   format      V393 V393F.;
   format      V394 V394F.;
   format      V395 V395F.;
   format      V399 V399F.;
   format      V400 V400F.;
   format      V401 V401F.;
   format      V403 V403F.;
   format      V406 V406F.;
   format      V407 V407F.;
   format      V408 V408F.;
   format      V409 V409F.;
   format      V410 V410F.;
   format      V412 V412F.;
   format      V415 V415F.;
   format      V416 V416F.;
   format      V417 V417F.;
   format      V418 V418F.;
   format      V419 V419F.;
   format      V420 V420F.;
   format      V421 V421F.;
   format      V422 V422F.;
   format      V423 V423F.;
   format      V424 V424F.;
   format      V425 V425F.;
   format      V428 V428F.;
   format      V429 V429F.;
   format      V431 V431F.;
   format      V432 V432F.;
   format      V433 V433F.;
   format      V435 V435F.;
   format      V436 V436F.;
   format      V437 V437F.;
   format      V438 V438F.;
   format      V439 V439F.;
   format      V440 V440F.;
   format      V441 V441F.;
quit;
