/* This Proc Format program was automatically generated by Stat/Transfer ver.14.2.1138.0513 */



libname library '/home/Carsten/Skrivebord/' ;

proc format library = library ;
   value V4F
      1 = 'Mand'  
      2 = 'Kvinde' ;
   value V6F
      1 = 'Gift'  
      2 = 'Samlevende i papirløst ægteskab'  
      3 = 'Skilt'  
      4 = 'Separeret'  
      5 = 'Enke/enkemand'  
      6 = 'Enlig, gå til spm. 5 (V8)' ;
   value V7F
      0 = 'Ingen gange (kan kun forekomme ved kode 2 i spm. 3 (V6))'  
      1 = 'Een gang'  
      2 = '2 gange'  
      3 = '3 gange eller flere'  
      10 = 'Irrelevant' ;
   value V8F
      1 = 'Ja'  
      2 = 'Nej' ;
   value V9F
      1 = 'Går i skole'  
      2 = '7. klasse eller mindre'  
      3 = '8. klasse + mellemskole uden eksamen'  
      4 = '9. klasse statskontrolleret prøve og folkeskolens afgangsprøve'  
      5 = 'Teknisk forberedelseseksamen'  
      6 = '10. klasse statskontrolleret prøve og folkeskolens udvidede afgangsprøver'  
      7 = 'Udvidet teknisk forberedelseseksamen'  
      8 = '1. real'  
      9 = '2. real'  
      10 = '3. real uden eksamen'  
      11 = 'Realkursus uden eksamen'  
      12 = 'Mellemskoleeksamen'  
      13 = 'Real-, pigeskole- og preliminæreksamen'  
      14 = 'Gymnmasium eller HF uden eksamen'  
      15 = 'Studenter- eller HF-eksamen'  
      16 = 'Andet (herunder udenlandsk skole)' ;
   value V10F
      1 = 'Ja, har een'  
      2 = 'Ja, er igang med at få een'  
      3 = 'Nej, gå til spm. 10 (V14)'  
      9 = 'Uoplyst' ;
   value V11F
      1 = 'Specialarbejderkursus, gå til spm. 10 (V14)'  
      2 = 'Faglig uddannelse (lærling, EFG-, fx kontor- assistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse, gå til spm. 10 (V14)'  
      4 = 'Handelshøjskole (korrespondent,HA,HD) eller bankuddannelse, gå til spm. 10 (V14)'  
      5 = '2-3 årig teknisk uddannelse (fx laborant, teknisk assistent, apoteksassistent, tandpleje) gå til spm. 10 (V14)'  
      6 = 'Videregående teknisk uddannelse, evt efter gennem- ført faglig udd., (fx maskin- el. byggetekniker, bygningskonstrukt'  
      7 = '1-årig uddannelse, indenfor social- og sundheds- væsenet (fx sygehjælper, beskæftigelsesvejleder) gå til spm. 10 (V'  
      8 = '3-4 årig uddannelse, indenfor social- og sundheds- væsenet (fx sygeplejerske, plejeassisten) gå til spm. 10 (V14)'  
      9 = '3-4 årig uddannelse indenfor undervisning og oplys- ning (fx børnehave-/fritidspædagog, folke- skolelærer, bibliotek'  
      10 = 'Kandidat fra universitet eller højere læreanstalt (fx gymnasielærer, civilingeniør, tandlæge, advokat) gå til spm.'  
      11 = 'Uddannet indenfor forsvar, politi, post- væsen, toldvæsen mv. gå til spm. 10 (V14)'  
      12 = 'Anden uddannnelse, hvilken?'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V13F
      1 = 'Jern og metal'  
      2 = 'Bygge- og anlæg'  
      3 = 'Grafiske fag'  
      4 = 'HK-området'  
      5 = 'Servicefagene'  
      6 = 'Jordbrug'  
      7 = 'Landtransport'  
      8 = 'Levnedsmidler'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V14F
      99 = 'Uoplyst' ;
   value V15F
      1 = 'Ja, gå til spm. 14 (V19)'  
      2 = 'Nej' ;
   value V16F
      1 = 'Studerende'  
      2 = 'Skoleelev'  
      3 = 'Pensionist'  
      4 = 'Husmor'  
      5 = 'Arbejdsløs'  
      6 = 'Efterløn'  
      7 = 'Langtidssyg'  
      8 = 'Værnepligtig'  
      9 = 'Andet, hvad?'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V18F
      1 = 'Ja, gå til spm. 15 (V21)'  
      2 = 'Nej, gå til spm. 20 (V26)'  
      10 = 'Irrelevant' ;
   value V19F
      1 = 'Ansat 30 timer om ugen eller mere'  
      2 = 'Ansat mindre end 30 timer om ugen'  
      3 = 'Selvstændig erhvervsdrivende, medhjælpende hustru'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V23F
      1 = 'Privat sektor'  
      2 = 'Staten'  
      3 = 'Amt'  
      4 = 'Kommune'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V24F
      1 = 'Selvstændig landmand'  
      2 = 'Selvstændig akademiker, evt. med 1-2 underordnede (advokat, ingeniør)'  
      3 = 'Medhjælpende ægtefælle'  
      4 = 'Ejer/direktør for virksomhed (hvis ikke kode 02) med 10 eller flere ansatte'  
      5 = 'Ejer/direktør for virksomhed (hvis ikke kode 02) med færre end 10 ansatte'  
      6 = 'Arbejder, faglært'  
      7 = 'Specialarbejder (dvs. ufaglært med efteruddannelseskurser)'  
      8 = 'Ufaglært arbejder'  
      9 = 'Formand, inspektør, funktionær med ledelsesopgaver'  
      10 = 'Funktionær med faguddannelse'  
      11 = 'Funktionær uden faguddannelse'  
      12 = 'Landarbejder'  
      13 = 'Ansat ved forsvaret'  
      14 = 'Lærling, EFG-elev i håndværksfag'  
      15 = 'Lærling, EFG-elev i butiks- eller kontorfag'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V25F
      1 = 'Ja, gå til spm. 27 (V32)'  
      2 = 'Nej' ;
   value V26F
      1 = 'Ja'  
      2 = 'Nej, gå til spm. 27 (V32)'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V27F
      1 = 'Ansat 30 timer om ugen eller mere'  
      2 = 'Ansat mindre end 30 timer om ugen'  
      3 = 'Selvstændig erhversdrivende, medhjælpende hustru'  
      10 = 'Irrelevant' ;
   value V31F
      1 = 'Selvstændig landmand'  
      2 = 'Selvstændig akademiker evt med 1-2 underordnede (advokat, ingeniør)'  
      3 = 'Medhjælpende ægtefælle'  
      4 = 'Ejer/direktør for virksomhed (hvis ikke kode 02) med 10 eller flere ansatte'  
      5 = 'Ejer/direktør for virksomhed (hvis ikke kode 02) med færre end 10 ansatte'  
      6 = 'Arbejder, faglært'  
      7 = 'Specialarbejder (dvs. ufaglært med efteruddannelseskurser)'  
      8 = 'Ufaglært arbejder'  
      9 = 'Formand, inspektør, funktionær med ledelsesopgaver'  
      10 = 'Funktionær med faguddannelse'  
      11 = 'Funktionær uden faguddannelse'  
      12 = 'Landarbejder'  
      13 = 'Ansat ved forsvaret'  
      14 = 'Lærling, EFG-elev i håndværksfag'  
      15 = 'Lærling, EFG-elev i butik/kontorfag'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V33F
      1 = '2.000 eller derunder'  
      2 = '2.001-5.000 indbyggere'  
      3 = '5.001-10.000 indbyggere'  
      4 = '10.001-20.000 indbyggere'  
      5 = '20.001-50.000 indbyggere'  
      6 = '50.001-100.000 indbyggere'  
      7 = '100.001 eller derover'  
      8 = 'Ved ikke' ;
   value V34F
      1 = 'Boede med en far og en mor'  
      2 = 'Boede kun med mor'  
      3 = 'Boede kun med far, gå til spm. 32 (V38)'  
      4 = 'Andet, gå til spm. 34 (V41)' ;
   value V35F
      0 = 'Ingen erhvervsuddannelse, gå til filter 1 (V41)'  
      1 = 'Specialarbejderkursus, gå til filter 1 (V41)'  
      2 = 'Faglig uddannelse (lærling, EFG-, fx kontor- assistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse'  
      4 = 'Handelshøjskole (korrespondent,HA,HD) eller bankuddannelse'  
      5 = '2-3 årig teknisk uddannelse (fx laborant, teknisk assisten, apoteksassistent, tandpleje)'  
      6 = 'Videregående teknisk uddannelse, evt. efter gennemført faglig uddannelse, (fx. maskin- eller byggetekniker, bygningsko'  
      7 = '1-årig uddannelse, indenfor social- og sundhedsvæsenet (fx sygehjælper,beskæftigelsesvejleder)'  
      8 = '3-4 årig uddannelse, indenfor social- og sundheds- væsenet (fx sygeplejerske, plejeassistent)'  
      9 = '3-4 årig uddannelse indenfor undervisning og oplysning (fx børnehave-/fritidspædagog, folkeskolelærer, bibliotekar,'  
      10 = 'Kandidat fra universitet eller højere læreanstalt (fx gymnasielærer, civilingeniør, tandlæge, advokat)'  
      11 = 'Uddannet indenfor forsvar, politi, postvæsen, toldvæsen mv.'  
      12 = 'Anden uddannelse, hvilken?'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V37F
      1 = 'Jern og metal'  
      2 = 'Bygge- og anlæg'  
      3 = 'Grafiske fag'  
      4 = 'HK-området'  
      5 = 'Servicefagene'  
      6 = 'Jordbrug'  
      7 = 'Landtransport'  
      8 = 'Levnedsmidler'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V38F
      0 = 'Ingen erhvervsuddannelse gå til filter 1 (V44)'  
      1 = 'Specialarbejderkursus gå til filter 1 (V44)'  
      2 = 'Faglig uddannelse (lærling, EFG-, fx kontor- assistent, typograf, snedker, frisør)'  
      3 = '1-årig handelseksamen, højere handelseksamen (HH), 1-2 årig EDB-uddannelse'  
      4 = 'Handelshøjskole (korrespondent, HA, HD) eller bankuddannelse'  
      5 = '2-3 årig teknisk uddannelse (fx laborant, teknisk assisten, apoteksassistent, tandpleje)'  
      6 = 'Videregående teknisk uddannelse, evt. efter gennemført faglig uddannelse, (fx. maskin- eller byggetekniker, bygningsko'  
      7 = '1-årig uddannelse, indenfor social- og sundheds- væsenet (fx sygehjælper, beskæftigelsesvejleder)'  
      8 = '3-4 årig uddannelse, indenfor social- og sundheds- væsenet (fx sygeplejerske, plejeassistent)'  
      9 = '3-4 årig uddannelse indenfor undervisning og oplysning (fx børnehave-/fritidspædagog, folkeskolelærer, bibliotekar,'  
      10 = 'Kandidat fra universitet eller højere læreanstalt (fx gymnasielærer, civilingeniør, tandlæge, advokat)'  
      11 = 'Uddannet indenfor forsvar, politi, postvæsen, toldvæsen mv.'  
      12 = 'Anden uddannelse, hvilken?'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V40F
      1 = 'Jern og metal'  
      2 = 'Bygge- og anlæg'  
      3 = 'Grafiske fag'  
      4 = 'HK-området'  
      5 = 'Servicefagene'  
      6 = 'Jordbrug'  
      7 = 'Landtransport'  
      8 = 'Levnedsmidler'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V41F
      1 = 'Ja'  
      2 = 'Nej' ;
   value V42F
      1 = 'Ja'  
      2 = 'Nej' ;
   value V43F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V44F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke' ;
   value V45F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V46F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V47F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V48F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke' ;
   value V49F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke ret vigtigt'  
      4 = 'Slet ikke vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V50F
      1 = 'Ofte'  
      2 = 'Nu og da'  
      3 = 'Aldrig'  
      9 = 'Uoplyst' ;
   value V51F
      1 = 'Aldrig (dvs. nej)'  
      2 = 'Ofte'  
      3 = 'Nu og da'  
      4 = 'Sjældent'  
      8 = 'Ved ikke' ;
   value V52F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V53F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V54F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V55F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V56F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V57F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke' ;
   value V58F
      1 = 'Meget lykkelig'  
      2 = 'Ret lykkelig'  
      3 = 'Ikke særlig lykkelig'  
      4 = 'Meget ulykkelig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V59F
      1 = 'Besvaret, gå til spm. 44 (V108)'  
      2 = 'Ikke besvaret' ;
   value V60F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.B (V62)'  
      10 = 'Irrelevant' ;
   value V61F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V62F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.C (V64)'  
      10 = 'Irrelevant' ;
   value V63F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V64F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.D (V66)'  
      10 = 'Irrelevant' ;
   value V65F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V66F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.E (V68)'  
      10 = 'Irrelevant' ;
   value V67F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V68F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.F (V70)'  
      10 = 'Irrelevant' ;
   value V69F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V70F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.G (V72)'  
      10 = 'Irrelevant' ;
   value V71F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V72F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.H (V74)'  
      10 = 'Irrelevant' ;
   value V73F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V74F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.I (V76)'  
      10 = 'Irrelevant' ;
   value V75F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V76F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.J (V78)'  
      10 = 'Irrelevant' ;
   value V77F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V78F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.K (V80)'  
      10 = 'Irrelevant' ;
   value V79F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V80F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.L (V82)'  
      10 = 'Irrelevant' ;
   value V81F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V82F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.M (V84)'  
      10 = 'Irrelevant' ;
   value V83F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V84F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.N (V86)'  
      10 = 'Irrelevant' ;
   value V85F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V86F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.O (V88)'  
      10 = 'Irrelevant' ;
   value V87F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V88F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.P (V90)'  
      10 = 'Irrelevant' ;
   value V89F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V90F
      1 = 'Besvaret'  
      2 = 'Ikke besvaret, gå til spm. 42.1 (V92)'  
      10 = 'Irrelevant' ;
   value V91F
      1 = 'Ja'  
      2 = 'Nej'  
      10 = 'Irrelevant' ;
   value V92F
      1 = 'Besvaret, gå til spm. 44 (V108)'  
      2 = 'Ikke besvaret'  
      10 = 'Irrelevant' ;
   value V93F
      1 = 'IP udfører ikke frivilligt, ubetalt arbejde, gå til spm. 44.A (V109)'  
      2 = 'IP udfører frivilligt, ubetalt arbejde'  
      10 = 'Irrelevant' ;
   value V94F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V95F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V96F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V97F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V98F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V99F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V100F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V101F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V102F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V103F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V104F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V105F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V106F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V107F
      1 = 'Ikke vigtigt'  
      5 = 'Meget vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V108F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V109F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V110F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V111F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V112F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V113F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V114F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V115F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V116F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V117F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V118F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V119F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V120F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V121F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V122F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V123F
      1 = 'Meget god'  
      2 = 'God'  
      3 = 'Nogenlunde'  
      4 = 'Dårlig'  
      5 = 'Meget dårlig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V124F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst' ;
   value V125F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V126F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V127F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V128F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V129F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst' ;
   value V130F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V131F
      1 = 'Ja'  
      2 = 'Nej'  
      9 = 'Uoplyst' ;
   value V132F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V133F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V134F
      1 = 'De fleste er til at stole på'  
      2 = 'Man kan ikke være for forsigtig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V135F
      1 = 'Overhovedet ingen indflydelse'  
      10 = 'Overordentlig megen indflydelse'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V136F
      1 = 'Meget utilfreds'  
      10 = 'Meget tilfreds'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V137F
      1 = 'Fordi de er uheldige'  
      2 = 'Fordi de er dovne og mangler viljestyrke'  
      3 = 'Fordi der er uretfærdighed i vort samfund'  
      4 = 'Det er en uundgåeligt resultat af den moderne udvikling'  
      5 = 'Ingen af disse grunde'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V138F
      1 = 'Fordi de er uheldige'  
      2 = 'Fordi de er dovne og mangler viljestyrke'  
      3 = 'Fordi der er uretfærdighed i vort samfund'  
      4 = 'Det er en uundgåeligt resultat af den moderne udvikling'  
      5 = 'Ingen af disse grunde'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V139F
      1 = 'Besvaret, gå til filter f3 (V155)'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V140F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V141F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V142F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V143F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V144F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V145F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V146F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V147F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V148F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V149F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V150F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V151F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V152F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V153F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V154F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V155F
      1 = 'IP er ikke i arbejde, gå til spm. 55 (V159)'  
      2 = 'IP er i arbejde' ;
   value V156F
      1 = 'Meget'  
      2 = 'Noget'  
      3 = 'Lidt'  
      4 = 'Slet ikke'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V157F
      1 = 'Utilfreds'  
      10 = 'Tilfreds'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V158F
      1 = 'Slet ingen frihed'  
      10 = 'Overordentlig stor frihed'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V159F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V160F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V161F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V162F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V163F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V164F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V165F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V166F
      1 = 'Besvaret'  
      2 = 'Ubesvaret' ;
   value V167F
      1 = 'Retfærdigt'  
      2 = 'Uretfærdigt'  
      8 = 'Ved ikke' ;
   value V168F
      1 = 'Ejerne bør selv lede deres virksomhed eller udnævne ledere'  
      2 = 'Ejerne og lønmodtagerne bør i fællesskab udvælge ledere'  
      3 = 'Staten bør være ejer og udnævne ledere'  
      4 = 'Lønmodtagere bør eje virksomheden og bør udvælge ledere'  
      8 = 'Ved ikke' ;
   value V169F
      1 = 'Man bør følge arbejdsinstruktionerne'  
      2 = 'Man må først være overbevist om, at disse er rigtige'  
      3 = 'Det kommer an på'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V170F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke' ;
   value V171F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke' ;
   value V172F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke' ;
   value V173F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke' ;
   value V174F
      1 = 'Utilfreds'  
      10 = 'Tilfreds'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V175F
      1 = 'Ofte'  
      2 = 'En gang imellem'  
      3 = 'Sjældent'  
      4 = 'Aldrig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V176F
      1 = 'Ofte'  
      2 = 'En gang imellem'  
      3 = 'Sjældent'  
      4 = 'Aldrig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V177F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V178F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V179F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V180F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V181F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V182F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V183F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken eller'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V184F
      1 = 'Mest enig i udsagn A'  
      2 = 'Mest enig i udsagn B'  
      3 = 'Hverken enig i udsagn A eller B'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V185F
      1 = 'Ja'  
      2 = 'Nej, gå til spm. 66 (V188)' ;
   value V186F
      1 = 'Romersk katolsk'  
      2 = 'Protestant (Den danske Folkekirke)'  
      3 = 'Jehovas Vidne, adventist, m.v.'  
      4 = 'Jøde'  
      5 = 'Muslim'  
      6 = 'Hindu'  
      7 = 'Buddhist'  
      8 = 'Anden, skriv hvilken'  
      10 = 'Irrelevant' ;
   value V188F
      1 = 'Ja'  
      2 = 'Nej, gå til spm. 67 (V191)'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V189F
      1 = 'Romersk katolsk'  
      2 = 'Protestant (Den danske Folkekirke)'  
      3 = 'Jehovas Vidne, adventist, m.v.'  
      4 = 'Jøde'  
      5 = 'Muslim'  
      6 = 'Hindu'  
      7 = 'Buddhist'  
      8 = 'Andet'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst'  
      100 = 'Irrelevant' ;
   value V191F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V192F
      1 = 'Oftere end 1 gang om ugen'  
      2 = 'Ca. 1 gang om ugen'  
      3 = 'Ca. 1 gang om måneden'  
      4 = 'Kun til jule-/påskegudstjeneste'  
      5 = 'Til andre højtider'  
      6 = 'Ca. 1 gang om året'  
      7 = 'Sjældnere end 1 gang om året'  
      8 = 'Aldrig, næsten aldrig'  
      9 = 'Uoplyst' ;
   value V193F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V194F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V195F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V196F
      1 = 'Et troende menneske'  
      2 = 'Et ikke troende menneske'  
      3 = 'Overbevist ateist'  
      8 = 'Ved ikke' ;
   value V197F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V198F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V199F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V200F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V201F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V202F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V203F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V204F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V205F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V206F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V207F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V208F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V209F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V210F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V211F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V212F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V213F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke' ;
   value V214F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V215F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V216F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V217F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V218F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V219F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V220F
      1 = 'Der er en personlig Gud'  
      2 = 'Der er en særlig åndelig kraft'  
      3 = 'Jeg ved ikke, hvad jeg skal tro på'  
      4 = 'Tror ikke, der er nogen form for åndelig kraft eller personlig Gud'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V221F
      1 = 'Ingen rolle'  
      10 = 'Meget stor rolle'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V222F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V223F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V224F
      1 = 'Ofte'  
      2 = 'Somme tider'  
      3 = 'Næsten aldrig'  
      4 = 'Kun i krisesituationer'  
      5 = 'Aldrig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V225F
      1 = 'Utilfreds'  
      10 = 'Tilfreds'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V226F
      1 = 'Ja, IP er enlig, gå til spm. 81 (V232)'  
      2 = 'Nej, IP er ikke enlig, gå til spm. 80 (V227)' ;
   value V227F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V228F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V229F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V230F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V231F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V232F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      10 = 'Irrelevant' ;
   value V233F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      10 = 'Irrelevant' ;
   value V234F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      10 = 'Irrelevant' ;
   value V235F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      10 = 'Irrelevant' ;
   value V236F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      10 = 'Irrelevant' ;
   value V237F
      1 = 'Enig'  
      2 = 'Uenig'  
      3 = 'Hverken enig eller uenig/det kommer an på'  
      8 = 'Ved ikke' ;
   value V238F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V239F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V240F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V241F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V242F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V243F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V244F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V245F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V246F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V247F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V248F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V249F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V250F
      1 = 'Meget vigtigt'  
      2 = 'Ret vigtigt'  
      3 = 'Ikke særlig vigtigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V251F
      1 = 'Ja'  
      2 = 'Nej, gå til spm. 86 (V255)'  
      9 = 'Uoplyst' ;
   value V252F
      1 = '1 barn'  
      2 = '2 børn'  
      3 = '3 børn'  
      4 = '4 børn'  
      5 = '5 børn'  
      6 = '6 børn eller flere'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V253F
      0 = 'Ingen'  
      1 = '1 barn'  
      2 = '2 børn'  
      3 = '3 børn'  
      4 = '4 børn'  
      5 = '5 børn'  
      6 = '6 børn eller flere'  
      9 = 'Uoplyst'  
      10 = 'Irrelevant' ;
   value V254F
      0 = 'Ingen børn'  
      1 = '1 barn'  
      2 = '2 børn'  
      3 = '3 børn'  
      4 = '4 børn'  
      5 = '5 børn'  
      6 = '6 børn'  
      8 = '8 børn'  
      9 = '9 børn'  
      10 = '10 børn eller flere'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V255F
      1 = 'Enig'  
      2 = 'Uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V256F
      1 = 'Væsentligt at få børn'  
      2 = 'Ikke væsentligt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V257F
      1 = 'Enig'  
      2 = 'Uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V258F
      1 = 'Ja'  
      2 = 'Nej'  
      3 = 'Det kommer an på'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V259F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V260F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V261F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V262F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V263F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V264F
      1 = 'Helt enig'  
      2 = 'Enig'  
      3 = 'Uenig'  
      4 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V265F
      1 = 'Mest enig i udsagn A'  
      2 = 'Mest enig i udsagn B'  
      3 = 'Ingen af delene'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V266F
      1 = 'A. Det er forældrenes pligt/ansvar at gøre alt hvad der står i deres magt, uanset om det skulle gå ud over deres ege'  
      2 = 'B. Forældre har deres eget liv, og man kan ikke forlange, at de skal ofre deres egen trivsel for børnenes skyld.'  
      3 = 'Ingen af delene'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V267F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V268F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V269F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V270F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V271F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V272F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V273F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V274F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V275F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V276F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V277F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V278F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V279F
      1 = 'Tilhænger'  
      2 = 'Modstander'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V280F
      1 = 'Tilhænger'  
      2 = 'Modstander'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V281F
      1 = 'Tilhænger'  
      2 = 'Modstander'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V282F
      1 = 'Tilhænger'  
      2 = 'Modstander'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V283F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Ikke særlig interesseret'  
      4 = 'Slet ikke interesseret'  
      9 = 'Uoplyst' ;
   value V284F
      1 = 'Har deltaget'  
      2 = 'Muligvis deltage'  
      3 = 'Aldrig deltage'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V285F
      1 = 'Har deltaget'  
      2 = 'Muligvis deltage'  
      3 = 'Aldrig deltage'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V286F
      1 = 'Har deltaget'  
      2 = 'Muligvis deltage'  
      3 = 'Aldrig deltage'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V287F
      1 = 'Har deltaget'  
      2 = 'Muligvis deltage'  
      3 = 'Aldrig deltage'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V288F
      1 = 'Har deltaget'  
      2 = 'Muligvis deltage'  
      3 = 'Aldrig deltage'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V289F
      1 = 'Enig i udsagn A'  
      2 = 'Enig i udsagn B'  
      3 = 'Hverken enig i udsagn A eller B'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V290F
      1 = 'Venstreorienteret'  
      10 = 'Højreorienteret'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V291F
      1 = 'Hele den måde vores samfund er opbygget på må ændres radikalt gennem revolution'  
      2 = 'Vores samfund bør gradvist forbedres gennem reformer'  
      3 = 'Vores nuværende samfund må ihærdigt forsvares mod alle undergravende kræfter'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V292F
      1 = 'Der bør være større lighed mellem folks indkomster'  
      10 = 'Personlig indsats bør belønnes bedre'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V293F
      1 = 'Privat ejerskab af virksomhederne bør fremmes'  
      10 = 'Off. ejerskab af virksomhederne bør fremmes'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V294F
      1 = 'Det enkelte menneske burde have mere ansvar for at sørge for sig selv'  
      10 = 'Det off. burde have mere ansvar for at sikre, at der bliver sørget for alle'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V295F
      1 = 'Hvis arb.løse ikke tager det arbejde, de bliver tilbudt, bør de miste deres arbejdsløshedsunderstøttelse'  
      10 = 'Arb.løse bør have ret til at afslå et job, de ikke ønsker'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V296F
      1 = 'Konkurrence er sundt. Det stimulerer folk til at arbejde hårdt og udvikle nye ideer.'  
      10 = 'Konkurrence er usundt. Det bringer det værste frem i mennesket.'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V297F
      1 = 'I det lange løb giver hårdt arbejde som regel succes i livet.'  
      10 = 'Det er ikke altid, hårdt arb. giver succes. Det er mere et spørgsmål om held og forbindelser.'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V298F
      1 = 'Folk kan kun samle rigdom på andres bekostning'  
      10 = 'Rigdom kan øges, så der er nok til alle'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V299F
      1 = 'At opretholde høj økonomisk vækst'  
      2 = 'At sørge for at landet har et stærkt forsvar'  
      3 = 'At lade folk være mere medbestemmende på job og i lokale spørgsmål'  
      4 = 'At gøre by og land smukkere'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V300F
      1 = 'At opretholde høj økonomisk vækst'  
      2 = 'At sørge for at landet har et stærkt forsvar'  
      3 = 'At lade folk være mere medbestemmende på job og i lokale spørgsmål'  
      4 = 'At gøre by og land smukkere'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V301F
      1 = 'At opretholde lov og orden i landet'  
      2 = 'At lade folk bestemme mere i vigtige regeringsbeslutninger'  
      3 = 'At bekæmpe stigende priser'  
      4 = 'At beskytte ytringsfriheden'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V302F
      1 = 'At opretholde lov og orden i landet'  
      2 = 'At lade folk bestemme mere i vigtige regeringsbeslutninger'  
      3 = 'At bekæmpe stigende priser'  
      4 = 'At beskytte ytringsfriheden'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V303F
      1 = 'At få stabiliseret økonomien'  
      2 = 'At arbejde for at få et mindre uper- sonligt, mere menneskeligt samfund'  
      3 = 'At arbejde for at få et samfund, hvor ideer har større betydning end penge'  
      4 = 'At bekæmpe kriminalitet'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V304F
      1 = 'At få stabiliseret økonomien'  
      2 = 'At arbejde for at få et mindre uper- sonligt, mere menneskeligt samfund'  
      3 = 'At arbejde for at få et samfund, hvor ideer har større betydning end penge'  
      4 = 'At bekæmpe kriminalitet'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V305F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V306F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V307F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V308F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V309F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V310F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V311F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V312F
      1 = 'Godt'  
      2 = 'Dårligt'  
      3 = 'Ligegyldigt'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V313F
      1 = 'Gavne'  
      2 = 'Skade'  
      3 = 'Både og'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V314F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V315F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V316F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V317F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V318F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V319F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V320F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V321F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V322F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V323F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V324F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V325F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V326F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V327F
      1 = 'Meget stor tillid'  
      2 = 'Ret stor tillid'  
      3 = 'Ikke særlig stor tillid'  
      4 = 'Slet ingen'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V328F
      1 = 'Går stærkt ind for'  
      2 = 'Går en del ind for'  
      3 = 'Går noget imod'  
      4 = 'Går stærkt imod'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V329F
      1 = 'Går stærkt ind for'  
      2 = 'Går en del ind for'  
      3 = 'Går noget imod'  
      4 = 'Går stærkt imod'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V330F
      1 = 'Går stærkt ind for'  
      2 = 'Går en del ind for'  
      3 = 'Går noget imod'  
      4 = 'Går stærkt imod'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V331F
      1 = 'Går stærkt ind for'  
      2 = 'Går en del ind for'  
      3 = 'Går noget imod'  
      4 = 'Går stærkt imod'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V332F
      1 = 'Går stærkt ind for'  
      2 = 'Går en del ind for'  
      3 = 'Går noget imod'  
      4 = 'Går stærkt imod'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V333F
      1 = 'Går stærkt ind for'  
      2 = 'Går en del ind for'  
      3 = 'Går noget imod'  
      4 = 'Går stærkt imod'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V334F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V335F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V336F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V337F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V338F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V339F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V340F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V341F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V342F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V343F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V344F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V345F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V346F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V347F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V348F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V349F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V350F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V351F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V352F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V353F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V354F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V355F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V356F
      1 = 'Slet ikke'  
      10 = 'I høj grad'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V357F
      1 = 'Den by eller det lokalområde jeg bor i'  
      2 = 'Den egn eller landsdel jeg bor i'  
      3 = 'Mit land'  
      4 = 'Europa'  
      5 = 'Verden'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V358F
      1 = 'Den by eller det lokalområde jeg bor i'  
      2 = 'Den egn eller landsdel jeg bor i'  
      3 = 'Mit land'  
      4 = 'Europa'  
      5 = 'Verden'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V359F
      1 = 'Meget stolt'  
      2 = 'Ret stolt'  
      3 = 'Ikke særlig stolt'  
      4 = 'Slet ikke stolt'  
      5 = 'Er ikke dansker'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V360F
      1 = 'Man skal være forsigtig med at fore- tage større forandringer i livet'  
      10 = 'Man kan aldrig opnå noget, med mindre man handler dristigt.'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V361F
      1 = 'Ideer, der har klaret tidens prøve, er som regel bedst'  
      10 = 'Nye ideer er som regel bedre end gamle'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V362F
      1 = 'Når der sker forandringer i mit liv, er jeg bekymret over de vanskeligheder, de kan medføre'  
      10 = 'Når der sker forandringer i mit liv, er jeg glad for muligheden for, at noget nyt begynder'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V363F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V364F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V365F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V366F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V367F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V368F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V369F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V370F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V371F
      1 = 'Besvaret'  
      2 = 'Ubesvaret'  
      9 = 'Uoplyst' ;
   value V372F
      1 = 'Helt enig'  
      2 = 'Noget enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Noget uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V373F
      1 = 'Helt enig'  
      2 = 'Noget enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Noget uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V374F
      1 = 'Helt enig'  
      2 = 'Noget enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Noget uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V375F
      1 = 'Helt enig'  
      2 = 'Noget enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Noget uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V376F
      1 = 'Helt enig'  
      2 = 'Noget enig'  
      3 = 'Hverken enig eller uenig'  
      4 = 'Noget uenig'  
      5 = 'Helt uenig'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V377F
      1 = 'Stor tillid'  
      2 = 'Nogen tillid'  
      3 = 'Hverken tillid eller mistillid'  
      4 = 'Nogen mistillid'  
      5 = 'Høj mistillid'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V378F
      1 = 'Stor tillid'  
      2 = 'Nogen tillid'  
      3 = 'Hverken tillid eller mistillid'  
      4 = 'Nogen mistillid'  
      5 = 'Høj mistillid'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V379F
      1 = 'Helt enig i udsagn A'  
      7 = 'Helt enig i udsagn B'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V380F
      1 = 'Ja'  
      2 = 'Nej'  
      8 = 'Ved ikke'  
      9 = 'Uoplyst' ;
   value V381F
      1 = 'Amerikanere'  
      3 = 'Englændere'  
      4 = 'Finner'  
      5 = 'Franskmænd'  
      6 = 'Tyskere'  
      7 = 'Islændinge'  
      8 = 'Nordmænd'  
      9 = 'Russere'  
      10 = 'Svenskere'  
      11 = 'Andre (skriv)'  
      12 = 'Ingen'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V383F
      1 = 'Amerikanere'  
      3 = 'Englændere'  
      4 = 'Finner'  
      5 = 'Franskmænd'  
      6 = 'Tyskere'  
      7 = 'Islændinge'  
      8 = 'Nordmænd'  
      9 = 'Russere'  
      10 = 'Svenskere'  
      11 = 'Andre (skriv)'  
      12 = 'Ingen'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V385F
      1 = 'Socialdemokratiet'  
      2 = 'Det radikale Venstre'  
      3 = 'Det konservative Folkeparti'  
      4 = 'Danmarks Retsforbund'  
      5 = 'Socialistisk Folkeparti'  
      6 = 'De Grønne'  
      7 = 'Det Humanistiske parti'  
      8 = 'Internationalen-Socialistisk Arbejderparti'  
      9 = 'Danmarks kommunistiske Parti'  
      10 = 'Marxistisk-Leninistisk Parti'  
      11 = 'Centrum-Demokraterne'  
      12 = 'Fælles Kurs'  
      13 = 'Kristeligt Folkeparti'  
      14 = 'Venstre, Danmarks liberale Parti'  
      15 = 'Venstresocialisterne'  
      16 = 'Fremskridtspartiet'  
      17 = 'Har ikke stemmeret'  
      18 = 'Vil ikke stemme'  
      19 = 'Enighedsliste'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V386F
      1 = 'Socialdemokratiet'  
      2 = 'Det radikale Venstre'  
      3 = 'Det konservative Folkeparti'  
      4 = 'Danmarks Retsforbund'  
      5 = 'Socialistisk Folkeparti'  
      6 = 'De Grønne'  
      7 = 'Det Humanistiske parti'  
      8 = 'Internationalen-Socialistisk Arbejderparti'  
      9 = 'Danmarks kommunistiske Parti'  
      10 = 'Marxistisk-Leninistisk Parti'  
      11 = 'Centrum-Demokraterne'  
      12 = 'Fælles Kurs'  
      13 = 'Kristeligt Folkeparti'  
      14 = 'Venstre, Danmarks liberale Parti'  
      15 = 'Venstresocialisterne'  
      16 = 'Fremskridtspartiet'  
      17 = 'Har ikke stemmeret'  
      18 = 'Vil ikke stemme'  
      19 = 'Enighedsliste'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V387F
      1 = 'Socialdemokratiet'  
      2 = 'Det radikale Venstre'  
      3 = 'Det konservative Folkeparti'  
      4 = 'Danmarks Retsforbund'  
      5 = 'Socialistisk Folkeparti'  
      6 = 'De Grønne'  
      7 = 'Det Humanistiske parti'  
      8 = 'Internationalen-Socialistisk Arbejderparti'  
      9 = 'Danmarks kommunistiske Parti'  
      10 = 'Marxistisk-Leninistisk Parti'  
      11 = 'Centrum-Demokraterne'  
      12 = 'Fælles Kurs'  
      13 = 'Kristeligt Folkeparti'  
      14 = 'Venstre, Danmarks liberale Parti'  
      15 = 'Venstresocialisterne'  
      16 = 'Fremskridtspartiet'  
      17 = 'Har ikke stemmeret'  
      18 = 'Vil ikke stemme'  
      19 = 'Enighedsliste'  
      88 = 'Ved ikke'  
      99 = 'Uoplyst' ;
   value V388F
      1 = 'Meget interesseret'  
      2 = 'Noget interesseret'  
      3 = 'Ikke interesseret'  
      9 = 'Uoplyst' ;
   value V390F
      1 = 'Mand'  
      2 = 'Kvinde'  
      9 = 'Uoplyst' ;
   value V392F
      101 = 'KØBENHAVN'  
      147 = 'FREDERIKSBERG'  
      151 = 'BALLERUP'  
      153 = 'BRØNDBY'  
      155 = 'DRAGØR'  
      157 = 'GENTOFTE'  
      159 = 'GLADSAXE'  
      161 = 'GLOSTRUP'  
      163 = 'HERLEV'  
      165 = 'ALBERTSLUND'  
      167 = 'HVIDOVRE'  
      169 = 'HØJE-TÅSTRUP'  
      171 = 'LEDØJE-SMØRUM'  
      173 = 'LYNGBY-TÅRBÆK'  
      175 = 'RØDOVRE'  
      181 = 'SØLLERØD'  
      183 = 'ISHØJ'  
      185 = 'TÅRNBY'  
      187 = 'VALLENSBÆK'  
      189 = 'VÆRLØSE'  
      201 = 'ALLERØD'  
      205 = 'BIRKERØD'  
      207 = 'FARUM'  
      208 = 'FREDENSBORG-HUMLEBÆK'  
      209 = 'FREDERIKSSUND'  
      211 = 'FREDERIKSVÆRK'  
      213 = 'GRÆSTED-GILLELEJE'  
      215 = 'HELSINGE'  
      217 = 'HELSINGØR'  
      219 = 'HILLERØD'  
      221 = 'HUNDESTED'  
      223 = 'HØRSHOLM'  
      225 = 'JÆGERSPRIS'  
      227 = 'KARLEBO'  
      229 = 'SKIBBY'  
      231 = 'SKÆVINGE'  
      233 = 'SLANGERUP'  
      235 = 'STENLØSE'  
      237 = 'ØLSTYKKE'  
      251 = 'BRAMSNÆS'  
      253 = 'GREVE'  
      255 = 'GUNDSØ'  
      257 = 'HVALSØ'  
      259 = 'KØGE'  
      261 = 'LEJRE'  
      263 = 'RAMSØ'  
      265 = 'ROSKILDE'  
      267 = 'SKOVBO'  
      269 = 'SOLRØD'  
      271 = 'VALLØ'  
      301 = 'BJERGSTED'  
      303 = 'DIANALUND'  
      305 = 'DRAGSHOLM'  
      307 = 'FUGLEBJERG'  
      309 = 'GØRLEV'  
      311 = 'HASHØJ'  
      313 = 'HASLEV'  
      315 = 'HOLBÆK'  
      317 = 'HVIDEBÆK'  
      319 = 'HØNG'  
      321 = 'JERNLØSE'  
      323 = 'KALUNDBORG'  
      325 = 'KORSØR'  
      327 = 'NYKØBING-RØRVIG'  
      329 = 'RINGSTED'  
      331 = 'SKÆLSKØR'  
      333 = 'SLAGELSE'  
      335 = 'SORØ'  
      337 = 'STENLILLE'  
      339 = 'SVINNINGE'  
      341 = 'TORNVED'  
      343 = 'TRUNDHOLM'  
      345 = 'TØLLØSE'  
      351 = 'FAKSE'  
      353 = 'FLADSÅ'  
      355 = 'HOLEBY'  
      357 = 'HOLMEGÅRD'  
      359 = 'HØJREBY'  
      361 = 'LANGEBÆK'  
      363 = 'MARIBO'  
      365 = 'MØN'  
      367 = 'NAKSKOV'  
      369 = 'NYKØBING F.'  
      371 = 'NYSTED'  
      373 = 'NÆSTVED'  
      375 = 'NØRRE ALSLEV'  
      377 = 'PRÆSTØ'  
      379 = 'RAVNSBORG'  
      381 = 'RUDBJERG'  
      383 = 'RØDBY'  
      385 = 'RØNNEDE'  
      387 = 'SAKSKØBING'  
      389 = 'STEVNS'  
      391 = 'STUBBEKØBING'  
      393 = 'SUSÅ'  
      395 = 'SYDFALSTER'  
      397 = 'VORDINGBORG'  
      401 = 'ALLINGE-GUDHJEM'  
      403 = 'HASLE'  
      405 = 'NEXØ'  
      407 = 'RØNNE'  
      409 = 'ÅKIRKEBY'  
      411 = 'CHRISTIANSØ'  
      421 = 'ASSENS'  
      423 = 'BOGENSE'  
      425 = 'BROBY'  
      427 = 'EGEBJERG'  
      429 = 'EJBY'  
      431 = 'FÅBORG'  
      433 = 'GLAMSBJERG'  
      435 = 'GUDME'  
      437 = 'HÅRBY'  
      439 = 'KERTEMINDE'  
      441 = 'LANGESKOV'  
      443 = 'MARSTAL'  
      445 = 'MIDDELFART'  
      447 = 'MUNKEBO'  
      449 = 'NYBORG'  
      451 = 'NØRRE-ÅBY'  
      461 = 'ODENSE'  
      471 = 'OTTERUP'  
      473 = 'RINGE'  
      475 = 'RUDKØBING'  
      477 = 'RYSLINGE'  
      479 = 'SVENDBORG'  
      481 = 'SYDLANGELAND'  
      483 = 'SØNDERSØ'  
      485 = 'TOMMERUP'  
      487 = 'TRANEKÆR'  
      489 = 'ULLERSLEV'  
      491 = 'VISSENBJERG'  
      493 = 'ÆRØSKØBING'  
      495 = 'ØRBÆK'  
      497 = 'ÅRSLEV'  
      499 = 'ÅRUP'  
      501 = 'AUGUSTENBORG'  
      503 = 'BOV'  
      505 = 'BREDEBRO'  
      507 = 'BROAGER'  
      509 = 'CHR-FELD'  
      511 = 'GRAM'  
      513 = 'GRÅSTEN'  
      515 = 'HADERSLEV'  
      517 = 'HØJER'  
      519 = 'LUNDTOFT'  
      521 = 'LØGUMKL.'  
      523 = 'NORDBORG'  
      525 = 'NR.RANGSTR.'  
      527 = 'RØDDING'  
      529 = 'RØDEKRO'  
      531 = 'SKÆRBÆK'  
      533 = 'SUNDEVED'  
      535 = 'SYDALS'  
      537 = 'SØNDERBORG'  
      539 = 'TINGLEV'  
      541 = 'TØNDER'  
      543 = 'VOJENS'  
      545 = 'ÅBENRÅ'  
      551 = 'BILLUND'  
      553 = 'BLÅBJERG'  
      555 = 'BLÅVANDSHUK'  
      557 = 'BRAMMING'  
      559 = 'BRØRUP'  
      561 = 'ESBJERG'  
      563 = 'FANØ'  
      565 = 'GRINDSTED'  
      567 = 'HELLE'  
      569 = 'HOLSTED'  
      571 = 'RIBE'  
      573 = 'VARDE'  
      575 = 'VEJEN'  
      577 = 'ØLGOD'  
      601 = 'BRÆDSTRUP'  
      603 = 'BØRKOP'  
      605 = 'EGTVED'  
      607 = 'FREDERICIA'  
      609 = 'GEDVED'  
      611 = 'GIVE'  
      613 = 'HEDENSTED'  
      615 = 'HORSENS'  
      617 = 'JELLING'  
      619 = 'JUELSMINDE'  
      621 = 'KOLDING'  
      623 = 'LUNDERSKOV'  
      625 = 'NØRRE-SNEDE'  
      627 = 'TØRRING-ULDUM'  
      629 = 'VAMDRUP'  
      631 = 'VEJLE'  
      651 = 'AULUM-HADERUP'  
      653 = 'BRANDE'  
      655 = 'EGVAD'  
      657 = 'HERNING'  
      659 = 'HOLMSLAND'  
      661 = 'HOLSTEBRO'  
      663 = 'IKAST'  
      665 = 'LEMVIG'  
      667 = 'RINGKJØBING'  
      669 = 'SKJERN'  
      671 = 'STRUER'  
      673 = 'THYBORØN-HARBOØRE'  
      675 = 'THYHOLM'  
      677 = 'TREHØJE'  
      679 = 'ULFBORG-VEMB'  
      681 = 'VIDEBÆK'  
      683 = 'VINDERUP'  
      685 = 'AASKOV'  
      701 = 'EBELTOFT'  
      703 = 'GALTEN'  
      705 = 'GJERN'  
      707 = 'GRENÅ'  
      709 = 'HADSTEN'  
      711 = 'HAMMEL'  
      713 = 'HINNERUP'  
      715 = 'HØRNING'  
      717 = 'LANGÅ'  
      719 = 'MARIAGER'  
      721 = 'MIDTDJURS'  
      723 = 'NØRHALD'  
      725 = 'NØRRE DJURS'  
      727 = 'ODDER'  
      729 = 'PURHUS'  
      731 = 'RANDERS'  
      733 = 'ROSENHOLM'  
      735 = 'ROUGSØ'  
      737 = 'RY'  
      739 = 'RØNDE'  
      741 = 'SAMSØ'  
      743 = 'SILKEBORG'  
      745 = 'SKANDERBORG'  
      747 = 'SØNDERHALD'  
      749 = 'THEM'  
      751 = 'ÅRHUS'  
      761 = 'BJERRINGBRO'  
      763 = 'FJENDS'  
      765 = 'HANSTHOLM'  
      767 = 'HVORSLEV'  
      769 = 'KARUP'  
      771 = 'KJELLERUP'  
      773 = 'MORSØ'  
      775 = 'MØLDRUP'  
      777 = 'SALLINGSUND'  
      779 = 'SKIVE'  
      781 = 'SPØTTRUP'  
      783 = 'SUNDSØRE'  
      785 = 'SYDTHY'  
      787 = 'THISTED'  
      789 = 'TJELE'  
      791 = 'VIBORG'  
      793 = 'ÅLESTRUP'  
      801 = 'ARDEN'  
      803 = 'BROVST'  
      805 = 'BRØNDERSLEV'  
      807 = 'DRONNINGLUND'  
      809 = 'FARSØ'  
      811 = 'FJERRITSLEV'  
      813 = 'FREDERIKSHAVN'  
      815 = 'HADSUND'  
      817 = 'HALS'  
      819 = 'HIRTSHALS'  
      821 = 'HJØRRING'  
      823 = 'HOBRO'  
      825 = 'LÆSØ'  
      827 = 'LØGSTØR'  
      829 = 'LØKKEN-VRÅ'  
      831 = 'NIBE'  
      833 = 'NØRAGER'  
      835 = 'PANDRUP'  
      837 = 'SEJLFLOD'  
      839 = 'SINDAL'  
      841 = 'SKAGEN'  
      843 = 'SKØRPING'  
      845 = 'STØVRING'  
      847 = 'SÆBY'  
      849 = 'ÅBYBRO'  
      851 = 'AALBORG'  
      861 = 'ÅRS' ;

proc datasets library = library ;
modify data1523;
   format        V4 V4F.;
   format        V6 V6F.;
   format        V7 V7F.;
   format        V8 V8F.;
   format        V9 V9F.;
   format       V10 V10F.;
   format       V11 V11F.;
   format       V13 V13F.;
   format       V14 V14F.;
   format       V15 V15F.;
   format       V16 V16F.;
   format       V18 V18F.;
   format       V19 V19F.;
   format       V23 V23F.;
   format       V24 V24F.;
   format       V25 V25F.;
   format       V26 V26F.;
   format       V27 V27F.;
   format       V31 V31F.;
   format       V33 V33F.;
   format       V34 V34F.;
   format       V35 V35F.;
   format       V37 V37F.;
   format       V38 V38F.;
   format       V40 V40F.;
   format       V41 V41F.;
   format       V42 V42F.;
   format       V43 V43F.;
   format       V44 V44F.;
   format       V45 V45F.;
   format       V46 V46F.;
   format       V47 V47F.;
   format       V48 V48F.;
   format       V49 V49F.;
   format       V50 V50F.;
   format       V51 V51F.;
   format       V52 V52F.;
   format       V53 V53F.;
   format       V54 V54F.;
   format       V55 V55F.;
   format       V56 V56F.;
   format       V57 V57F.;
   format       V58 V58F.;
   format       V59 V59F.;
   format       V60 V60F.;
   format       V61 V61F.;
   format       V62 V62F.;
   format       V63 V63F.;
   format       V64 V64F.;
   format       V65 V65F.;
   format       V66 V66F.;
   format       V67 V67F.;
   format       V68 V68F.;
   format       V69 V69F.;
   format       V70 V70F.;
   format       V71 V71F.;
   format       V72 V72F.;
   format       V73 V73F.;
   format       V74 V74F.;
   format       V75 V75F.;
   format       V76 V76F.;
   format       V77 V77F.;
   format       V78 V78F.;
   format       V79 V79F.;
   format       V80 V80F.;
   format       V81 V81F.;
   format       V82 V82F.;
   format       V83 V83F.;
   format       V84 V84F.;
   format       V85 V85F.;
   format       V86 V86F.;
   format       V87 V87F.;
   format       V88 V88F.;
   format       V89 V89F.;
   format       V90 V90F.;
   format       V91 V91F.;
   format       V92 V92F.;
   format       V93 V93F.;
   format       V94 V94F.;
   format       V95 V95F.;
   format       V96 V96F.;
   format       V97 V97F.;
   format       V98 V98F.;
   format       V99 V99F.;
   format      V100 V100F.;
   format      V101 V101F.;
   format      V102 V102F.;
   format      V103 V103F.;
   format      V104 V104F.;
   format      V105 V105F.;
   format      V106 V106F.;
   format      V107 V107F.;
   format      V108 V108F.;
   format      V109 V109F.;
   format      V110 V110F.;
   format      V111 V111F.;
   format      V112 V112F.;
   format      V113 V113F.;
   format      V114 V114F.;
   format      V115 V115F.;
   format      V116 V116F.;
   format      V117 V117F.;
   format      V118 V118F.;
   format      V119 V119F.;
   format      V120 V120F.;
   format      V121 V121F.;
   format      V122 V122F.;
   format      V123 V123F.;
   format      V124 V124F.;
   format      V125 V125F.;
   format      V126 V126F.;
   format      V127 V127F.;
   format      V128 V128F.;
   format      V129 V129F.;
   format      V130 V130F.;
   format      V131 V131F.;
   format      V132 V132F.;
   format      V133 V133F.;
   format      V134 V134F.;
   format      V135 V135F.;
   format      V136 V136F.;
   format      V137 V137F.;
   format      V138 V138F.;
   format      V139 V139F.;
   format      V140 V140F.;
   format      V141 V141F.;
   format      V142 V142F.;
   format      V143 V143F.;
   format      V144 V144F.;
   format      V145 V145F.;
   format      V146 V146F.;
   format      V147 V147F.;
   format      V148 V148F.;
   format      V149 V149F.;
   format      V150 V150F.;
   format      V151 V151F.;
   format      V152 V152F.;
   format      V153 V153F.;
   format      V154 V154F.;
   format      V155 V155F.;
   format      V156 V156F.;
   format      V157 V157F.;
   format      V158 V158F.;
   format      V159 V159F.;
   format      V160 V160F.;
   format      V161 V161F.;
   format      V162 V162F.;
   format      V163 V163F.;
   format      V164 V164F.;
   format      V165 V165F.;
   format      V166 V166F.;
   format      V167 V167F.;
   format      V168 V168F.;
   format      V169 V169F.;
   format      V170 V170F.;
   format      V171 V171F.;
   format      V172 V172F.;
   format      V173 V173F.;
   format      V174 V174F.;
   format      V175 V175F.;
   format      V176 V176F.;
   format      V177 V177F.;
   format      V178 V178F.;
   format      V179 V179F.;
   format      V180 V180F.;
   format      V181 V181F.;
   format      V182 V182F.;
   format      V183 V183F.;
   format      V184 V184F.;
   format      V185 V185F.;
   format      V186 V186F.;
   format      V188 V188F.;
   format      V189 V189F.;
   format      V191 V191F.;
   format      V192 V192F.;
   format      V193 V193F.;
   format      V194 V194F.;
   format      V195 V195F.;
   format      V196 V196F.;
   format      V197 V197F.;
   format      V198 V198F.;
   format      V199 V199F.;
   format      V200 V200F.;
   format      V201 V201F.;
   format      V202 V202F.;
   format      V203 V203F.;
   format      V204 V204F.;
   format      V205 V205F.;
   format      V206 V206F.;
   format      V207 V207F.;
   format      V208 V208F.;
   format      V209 V209F.;
   format      V210 V210F.;
   format      V211 V211F.;
   format      V212 V212F.;
   format      V213 V213F.;
   format      V214 V214F.;
   format      V215 V215F.;
   format      V216 V216F.;
   format      V217 V217F.;
   format      V218 V218F.;
   format      V219 V219F.;
   format      V220 V220F.;
   format      V221 V221F.;
   format      V222 V222F.;
   format      V223 V223F.;
   format      V224 V224F.;
   format      V225 V225F.;
   format      V226 V226F.;
   format      V227 V227F.;
   format      V228 V228F.;
   format      V229 V229F.;
   format      V230 V230F.;
   format      V231 V231F.;
   format      V232 V232F.;
   format      V233 V233F.;
   format      V234 V234F.;
   format      V235 V235F.;
   format      V236 V236F.;
   format      V237 V237F.;
   format      V238 V238F.;
   format      V239 V239F.;
   format      V240 V240F.;
   format      V241 V241F.;
   format      V242 V242F.;
   format      V243 V243F.;
   format      V244 V244F.;
   format      V245 V245F.;
   format      V246 V246F.;
   format      V247 V247F.;
   format      V248 V248F.;
   format      V249 V249F.;
   format      V250 V250F.;
   format      V251 V251F.;
   format      V252 V252F.;
   format      V253 V253F.;
   format      V254 V254F.;
   format      V255 V255F.;
   format      V256 V256F.;
   format      V257 V257F.;
   format      V258 V258F.;
   format      V259 V259F.;
   format      V260 V260F.;
   format      V261 V261F.;
   format      V262 V262F.;
   format      V263 V263F.;
   format      V264 V264F.;
   format      V265 V265F.;
   format      V266 V266F.;
   format      V267 V267F.;
   format      V268 V268F.;
   format      V269 V269F.;
   format      V270 V270F.;
   format      V271 V271F.;
   format      V272 V272F.;
   format      V273 V273F.;
   format      V274 V274F.;
   format      V275 V275F.;
   format      V276 V276F.;
   format      V277 V277F.;
   format      V278 V278F.;
   format      V279 V279F.;
   format      V280 V280F.;
   format      V281 V281F.;
   format      V282 V282F.;
   format      V283 V283F.;
   format      V284 V284F.;
   format      V285 V285F.;
   format      V286 V286F.;
   format      V287 V287F.;
   format      V288 V288F.;
   format      V289 V289F.;
   format      V290 V290F.;
   format      V291 V291F.;
   format      V292 V292F.;
   format      V293 V293F.;
   format      V294 V294F.;
   format      V295 V295F.;
   format      V296 V296F.;
   format      V297 V297F.;
   format      V298 V298F.;
   format      V299 V299F.;
   format      V300 V300F.;
   format      V301 V301F.;
   format      V302 V302F.;
   format      V303 V303F.;
   format      V304 V304F.;
   format      V305 V305F.;
   format      V306 V306F.;
   format      V307 V307F.;
   format      V308 V308F.;
   format      V309 V309F.;
   format      V310 V310F.;
   format      V311 V311F.;
   format      V312 V312F.;
   format      V313 V313F.;
   format      V314 V314F.;
   format      V315 V315F.;
   format      V316 V316F.;
   format      V317 V317F.;
   format      V318 V318F.;
   format      V319 V319F.;
   format      V320 V320F.;
   format      V321 V321F.;
   format      V322 V322F.;
   format      V323 V323F.;
   format      V324 V324F.;
   format      V325 V325F.;
   format      V326 V326F.;
   format      V327 V327F.;
   format      V328 V328F.;
   format      V329 V329F.;
   format      V330 V330F.;
   format      V331 V331F.;
   format      V332 V332F.;
   format      V333 V333F.;
   format      V334 V334F.;
   format      V335 V335F.;
   format      V336 V336F.;
   format      V337 V337F.;
   format      V338 V338F.;
   format      V339 V339F.;
   format      V340 V340F.;
   format      V341 V341F.;
   format      V342 V342F.;
   format      V343 V343F.;
   format      V344 V344F.;
   format      V345 V345F.;
   format      V346 V346F.;
   format      V347 V347F.;
   format      V348 V348F.;
   format      V349 V349F.;
   format      V350 V350F.;
   format      V351 V351F.;
   format      V352 V352F.;
   format      V353 V353F.;
   format      V354 V354F.;
   format      V355 V355F.;
   format      V356 V356F.;
   format      V357 V357F.;
   format      V358 V358F.;
   format      V359 V359F.;
   format      V360 V360F.;
   format      V361 V361F.;
   format      V362 V362F.;
   format      V363 V363F.;
   format      V364 V364F.;
   format      V365 V365F.;
   format      V366 V366F.;
   format      V367 V367F.;
   format      V368 V368F.;
   format      V369 V369F.;
   format      V370 V370F.;
   format      V371 V371F.;
   format      V372 V372F.;
   format      V373 V373F.;
   format      V374 V374F.;
   format      V375 V375F.;
   format      V376 V376F.;
   format      V377 V377F.;
   format      V378 V378F.;
   format      V379 V379F.;
   format      V380 V380F.;
   format      V381 V381F.;
   format      V383 V383F.;
   format      V385 V385F.;
   format      V386 V386F.;
   format      V387 V387F.;
   format      V388 V388F.;
   format      V390 V390F.;
   format      V392 V392F.;
quit;
